### ISSUE TITLE
New release: Kiwix JS Windows UWP 1.0.0

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#109]
Kiwix JS Windows is now reached version 1.0.0 and is out of beta!

A significant milestone of this version is support for ZIMs encoded with ZSTD compression. Once these ZIMs are publicly available, the app's stability (memory usage) and speed of decoding will be noticeably improved. The app retains compatibility with XZ-encoded ZIMs.

A signed version of the binary for sideloading is available from https://github.com/kiwix/kiwix-js-windows/releases/tag/v1.0.0 and from the Microsoft Store after certification.

**Comment by Jaifroid** [comment]
@kelson42 Would you kindly be able to update the release package on `download.kiwix.org` with the following signed package?:

https://github.com/kiwix/kiwix-js-windows/releases/download/v1.0.0/KiwixWebApp_1.0.0.0_AnyCPU.appxbundle 

Hopefully this bundle is now in line with Kiwix release numbering 😉. The package should be numbered 1.0.0. (The last extra 0 in the package name is added by Visual Studio to track different device types and can safely be ignored: it is always 0 for this app.)

**Comment by kelson42** [comment]
@Jaifroid This is a super great news! Congratulation for all the work and your perseverance.

I have upload the file at https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows_1.0.0.appxbundle.

FYI, I have been creating new ZIM files dedicated for Android custom apps with (1) not ft index (2) zstd (3) soon: webp in place of jpeg, png, gif. The recipe is here https://farm.openzim.org/recipes/wikipedia_en_medicine_app. The attemps is to create smaller ZIM files. This might be usefull for you as well.

**Comment by Jaifroid** [comment]
Thank you @kelson42 for your kind words!

That's interesting about the Android custom apps, as it sounds like we could support those ZIMs so long as they are published as ZIMs and not only as `apk` packages. The only thing we might need is a webp polyfill, which is readily available (and may be included in the ZIM as you said in another thread).

**Comment by Jaifroid** [comment]
@kelson42 The permalink https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows.appxbundle that appears on the Kiwix.org download page doesn't appear to be working -- it's linking to a very old package 0.9.9.990 instead of the latest: 1.0.0. How can we keep this up-to-date, please?:

![image](https://user-images.githubusercontent.com/4304337/93972011-5d7ba880-fd69-11ea-9588-eff050040a49.png)

**Comment by kelson42** [comment]
```
$ curl -I https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows.appxbundle
HTTP/2 301 
server: nginx/1.17.6
date: Wed, 23 Sep 2020 08:02:34 GMT
content-type: text/html; charset=iso-8859-1
location: https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows_1.0.0.appxbundle
cache-control: no-store, no-cache, must-revalidate
```

URL is correct and cache control is correct. Maybe a cache problem on your end?

**Comment by Jaifroid** [comment]
Thank you @kelson42 : I must have tried too early this morning before the overnight refresh had filtered through. Now the download link downloads the correct package. Sorry for false alarm!
