### ISSUE TITLE
Have an automatic way to synchronize the source code with kiwix-js

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js-windows#11]
Currently, the code of kiwix-js is duplicated here, with a few modifications.
Some of these code modifications are currently being applied upstream (in kiwix-js).
But there will still be some windows-specific modifications (like #4, or adding the BOM in UTF-8 files see kiwix/kiwix-js#266).

An idea would be to have a script here that does all the synchronization stuff.
I had a few ideas coming from the java ecosystem (ant for example), but choose a technology that you prefer, and that is more adequate to the Microsoft ecosystem.

It could take as a parameter : 
- a branch name
- or a commit id
- or a tag name

and would do the following : 
- download a zip of the source code of kiwix-js through a URL like https://github.com/kiwix/kiwix-js/archive/master.zip
- unzip the necessary files locally, overwriting the existing ones
- add the BOM header to the files that need it
- apply some patches (using the diff file format, or any other method you like)

It's just a suggestion, there might be better ways to do that.

**Comment by Jaifroid** [comment]
I think the code bases of each app are now too far apart to do this automatically, and we just have to use the traditional methods of backporting changes from one code base to another.
