### ISSUE TITLE
New release: Portable Kiwix JS WikiMed Electron Edition 1.0.2E for any 32bit/64bit Windows 7/8/10

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#114]
Announcing v1.0.2E of the portable release of the packaged WikiMed app for any Windows 7/8/10 based on the Electron platform:

https://kiwix.github.io/kiwix-js-windows/wikimed-electron.html 

This includes the latest WikiMed English ZIM archive dated 3 November 2020, `wikipedia_en_medicine_maxi_2020-11.zim` together with the changes in the [CHANGELOG](https://github.com/kiwix/kiwix-js-windows/blob/Kiwix-JS-WikiMed/CHANGELOG.md),

**Comment by kelson42** [comment]
@Jaifroid Why not using the ZIM of https://farm.openzim.org/recipes/wikipedia_en_medicine_app ? It is significantly smaller but provides the same content.

**Comment by Jaifroid** [comment]
@kelson42 Thank you! I've downloaded it, and it works fine in the UWP packaged app I am in the process of preparing. So I'll use this version going forwards.

**Comment by kelson42** [comment]
@Jaifroid Great, just to be clear about what it is. This is the same as before but:
* With zstd
* With Webp
* Without Xapian fulltext index

**Comment by Jaifroid** [comment]
@kelson42 I've now tested this on a Windows Mobile VM, and unfortunately WebP is not supported, so I will have to attach the WebP polyfill before I can use this ZIM in the UWP app (because the app runs in jQuery mode on Mobile, it is not automatically attached even if the polyfill is included in this version of the ZIM). On the desktop UWP app (same code base) WebP is natively supported. Windows Mobile is no longer being developed, so it will never support WebP natively. I think we still have quite a lot of Windows Mobile users, however, especially in less developed areas of the world and amongst enthusiasts, so I should support WebP.
