### ISSUE TITLE
Bad release filename on download.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#124]
There is a new release file at https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows_0.0.0.appxbundle.

It looks like an attempt to release automatically, which is great but I have a few questions:
* Is that an automatic release?
* Name is wrong, should I delte it or rename it? to what?

**Comment by Jaifroid** [comment]
@kelson42 Yes, I've implemented automatic release, and this is just a test release. It could be deleted. I have yet to test on a real release.

**Comment by kelson42** [comment]
I have deleted it.
