### ISSUE TITLE
Add print subroutine and print button

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#13]
The code for printing from a UWP app is specific to the platform, so should be added here rather than upstream in kiwix-js. However, a print button may be useful in upstream. Will suggest backporting print button once implemented here.

**Comment by Jaifroid** [comment]
Commit https://github.com/kiwix/kiwix-js-windows/commit/95c20916a23fff10ed06a70c37a5a19e5af58b5e now supports printing the iframe content. 

I didn't end up using UWP-specific routines, because they provide no advantage. A simple `window.frames[0].frameElement.contentWindow.print();` is enough to send (only) the iframe contents to the printer.

However, I've also added a filtering box (first screenshot below) so the user can set the `@media print` style in the iframe header (see the [code here](https://github.com/kiwix/kiwix-js-windows/commit/95c20916a23fff10ed06a70c37a5a19e5af58b5e#diff-764ebb2c13f00a104681b9e5f0327d3bR166)) to filter out certain elements if not required. I'm using the standard bootstrap modal for the first box below.

@mossroy, the code works in Firefox (though the print dialogue is the standard Firefox one, without the preview shown below) so some version of this code could easily be backported to kiwix-js. Printing in kiwix-js currently doesn't work properly, because the browser attempts to print only what is shown in the app, and doesn't pick up the iframe document (only). As a result, elements of the app get printed, and only one page is printed even if a long document is in the iframe. A port could be as simple as intercepting Ctrl-P and replacing it with `window.frames[0].frameElement.contentWindow.print();`.

For kiwix-js-windows, I've intercepted Ctrl-P, but I've also commandeered the About button. When a document is being shown, the About button changes to a Print glyphicon. To get to About, it is sufficient to go to Config, at which point the Print icon changes back to the About button. This is probably a temporary solution, but there is no space to add more buttons on small devices. Kiwix JS uses the hamburger menu, so no problem adding a print button there.

![image](https://user-images.githubusercontent.com/4304337/37298137-72504288-2617-11e8-9505-d3931e12bdcc.png)

![image](https://user-images.githubusercontent.com/4304337/37298219-a6585890-2617-11e8-98ff-32a903149f88.png)

**Comment by mossroy** [comment]
That's cool! I did notice that issue.
It looks simple to backport it, so please create an issue in kiwix-js for that.

**Comment by Jaifroid** [comment]
A reminder to myself that I need to add code to warn the user in cases where all images have not yet been extracted from the ZIM, or else force completion of image extraction if user has requested printing of images, before displaying the system print dialogue (latter is preferable).

**Comment by Jaifroid** [comment]
Commit https://github.com/kiwix/kiwix-js-windows/commit/07b3c1f84a0dfd599ef85ee093062dbd07ba9778 now preloads all remaining images if the user invokes the Print dialogue, and if the user has requested the display of images in Config.

**Comment by Jaifroid** [comment]
This has now been added to all three apps.
