### ISSUE TITLE
Open all headings option is partially broken

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#132]
The option to open all headings in an article only works in jQuery mode on recent ZIMs.

**Comment by kelson42** [comment]
@Jaifroid A regression?

**Comment by Jaifroid** [comment]
@kelson42 It's not a regression in the ZIM JavaScript, it is just a regression in my Kiwix JS Windows app! (It shouldn't be hard to fix.) This is a custom option in the app which allows the user to specify that headings should always be open. It is only broken in contexts where Service Worker is supported (PWA, Electron, NWJS), not in the main UWP app.

It would be nice if an option to open all headers no matter what the screen size were available as part of the planned API for Wikimedia ZIMs. However, if it is a niche case, it can continue to be handled in the reader(s).

**Comment by Jaifroid** [comment]
Partially fixed: it now works correctly in Service Worker mode. However, in jQuery mode, headings are ALWAYS open regardless of the setting in Configuration. Needs further work.

**Comment by Jaifroid** [comment]
But not fully fixed in IE11. See #202.
