### ISSUE TITLE
Query about serving code from secure server to enable Service Worker mode in the app

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#137]
@kelson42 A bit of advice, please. I can now enable Service Worker mode in the UWP app if (inside the app) it changes its address from local code to a secure server capable of serving `https:`. It effectively then runs as a Service-Worker-driven PWA, needing one-time access to the server to cache its own code using the Cache API. It then runs fully offline (apart from self-updating if a new Service worker is released on the server, and if the server is accessible). If running in a UWP shell, it also has access the full WinRT APIs for FS access, etc.

This is a big advance for users of the UWP app, as they can now use the dynamic UI with Gutenberg, TED, PhET, etc. This will be release 1.2 of the app (currently 1.1.4).

To enable this, I am currently serving the code from GitHub:

https://kiwix.github.io/kiwix-js-windows/

(This can also be launched as a PWA taking advantage of the File System Access API in recent Chromium browsers.)

While I would be perfectly happy serving it from there in princple, I understand there are sound reasons for not handing over too much control to one corporation, and further I use that implementation for development, bug-fixing and test releases where I need to test the behaviour of the app when served from a secure domain. So it's not ideal for a stable production app.

What would you suggest here? I see two alternatives:

1. A slot on the Kiwix server, but I'd need credentials / secret. In theory I could create a folder on `download.kiwix.org` with the existing CI secret, but I don't know if it's the appropriate server to serve dynamic app code, and I'd need to agree a folder location with you;
2. I could make a separate "production" folder on the GitHub site, e.g. `https://kiwix.github.io/kiwix-js-windows/pwa/` which would have a stable version of the code in it only updated with an official release. This has the advantage of being easy for me to update. One disadvantage is that it duplicates code on the server.

**Comment by kelson42** [comment]
@Jaifroid I'm really not familliar with the PWA, so sorry f I propose something which does not help. I could propose to declare pwa.kiwix.org DNS entry, you could build and publish automatically a Docker container, and we would deploy it in the cloud?

**Comment by Jaifroid** [comment]
A PWA is very lightweight: it's an installable web app served from a simple web server. So I think a VM would probably be overkill: I'm just serving an index.html and a number of JavaScript and css assets in subdirectories - nothing fancy or dynamic server-side. Would something like `https://download.kiwix.org/release/kiwix-js-windows/pwa/` be acceptable to start with? It could always be changed later, or we could point `pwa.kiwix.org` to that directory.

**Comment by kelson42** [comment]
@Jaifroid It is an elaborate solution but still pretty easy to do (basically only the Dockerfile with 5 lines) and cleaner/robuster than putting things on download.kiwix.org. Maybe I should just make a PR to show you, if you are not familliar with Docker. See https://stackoverflow.com/questions/31798849/how-to-serve-static-files-with-nginx-inside-of-a-docker-container

**Comment by Jaifroid** [comment]
OK, I have no experience with Docker! If it's as simple as a few lines... A PR would be welcome as an example, if it's not a big bother!

**Comment by kelson42** [comment]
@Jaifroid which files exactly should be moved to the web server? Do the need to be somehow modified?

**Comment by Jaifroid** [comment]
The required files are:
```
      "pwabuilder-sw.js",
      "index.html",
      "CHANGELOG.md",
      "LICENCE",
      "www/**",
      "archives/README.md"
```
`www/**` needs to include all files and subdirectories recursively. If that's not possible to code with wildcards, there is a full list in the Service Worker here:

https://github.com/kiwix/kiwix-js-windows/blob/master/pwabuilder-sw.js#L18

Many thanks!

**Comment by Jaifroid** [comment]
PS I added `manifest.json` to the list above. PWAs require that file.

**Comment by Jaifroid** [comment]
> Do they need to be modified?

No, no modification needed!

**Comment by kelson42** [comment]
@Jaifroid Available at https://pwa.kiwix.org, will be released again automatically on each new release (git tag).

**Comment by Jaifroid** [comment]
Wow, that's brilliant, thank you so much @kelson42! Very speedy!

It's working fine, and is offering to install the PWA if visited in a modern browser that supports [beforeinstallprompt](https://developer.mozilla.org/en-US/docs/Web/API/Window/onbeforeinstallprompt), and I'll be able to use this in the next release of the UWP app to enable Service Worker / PWA mode inside the app.

**Comment by Jaifroid** [comment]
Quick question @kelson42 : will Docker Hub update the container with any tag of whatever format created on the master branch, or does it need tags in a specific format (like dots and numbers only)? I currently use `v1.1.1` (`v`, dots and numbers), but it's completely fine with no filter as well.

**Comment by kelson42** [comment]
@Jaifroid Any tag with x.y.z in it ( you can have a suffix and prefix).
