### ISSUE TITLE
Docker container not updating

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#139]
@kelson42 The Docker build seems to be encountering an error. I created tag and release `v1.2.0` over two hours ago, and when I look at the commit details, I see a Docker failure as in screenshot below (top left). When I hover over the unsuccessful run, I get a message "Your image failed to build in Docker Hub". However, when I click "details" I get a 404 not found Docker Hub page. You can see this for yourself by going to the commit https://github.com/kiwix/kiwix-js-windows/commit/7c443d045f3b63610da4307339978abab796c871 and clicking the red cross top left. I don't think I can log in to Docker Hub, so I can't investigate further, otherwise I'd try to fix it myself.

![image](https://user-images.githubusercontent.com/4304337/107153220-39111900-6964-11eb-958f-9e1bb68b0fdd.png)

**Comment by Jaifroid** [comment]
Hmm, looking at my commit log, I see a Docker Hub failure on every commit (red crosses in image below). Yet it should only run on creating a new tag, no? Or maybe it runs on each push and checks if the commit is a tag. In any case, it's failing either way.

![image](https://user-images.githubusercontent.com/4304337/107153436-817d0680-6965-11eb-8ddc-9dea15552726.png)

**Comment by Jaifroid** [comment]
@kelson42 Is there any way I can debug this? I was wondering if the repo needs to add a secret or an access token, or vice versa (add an access token or other authorization to the docker cloud script so that it can interact with this repo)?

**Comment by kelson42** [comment]
@Jaifroid I will have a look, just a bit short on time.

**Comment by kelson42** [comment]
@Jaifroid The Docker Hub building rules where buggy. Hopefully this is better now. You can check the builds of Docker images at https://hub.docker.com/repository/docker/kiwix/kiwix-pwa.

**Comment by kelson42** [comment]
@Jaifroid I close the ticket as I believe this is fixed, please let me know or reopen the ticket if anything is unclear or need further work.

**Comment by Jaifroid** [comment]
Thank you very much, @kelson42! It's now updated to the latest version, so I can release the UWP side of the app (the two join up).
