### ISSUE TITLE
MathML in Proofwiki not showing correctly

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#154]
This should be a simple fix to the MathML detection regex.

**Comment by kelson42** [comment]
This is a problem with upstream web site or mwoffliner. There is a ticket and analysis at mwoffliner.

**Comment by Jaifroid** [comment]
Ah, OK. Though there seems to be another issue with `proofwiki_en_all_maxi_2021-05.zim`: it doesn't have any titles in the title pointer list (other than main page) so it's impossible to search for the ZIM contents... EDIT: I've just seen this ZIM is only 991K, so it looks like a failed scrape in any case.

**Comment by Jaifroid** [comment]
With latest ProofWiki, I can convert SOME of the equations, but many have unknown control sequences that the Math processor doesn't understand. It looks like the original MathJax configuration was not captured, as equations are not converted on library.kiwix.org (none of them).

**Comment by Jaifroid** [comment]
With the changes in commit https://github.com/kiwix/kiwix-js-windows/commit/2dd5bc3641b3a98468e48d0717141804b53b4e5b, we can now partially display equations in ProofWiki. However, there are a lot of custom macros that are simply not recognized by KaTeX. These are shown in red (see screenshot).

Ultimately, it won't be possible to support fully MathML in ProofWiki until the configuration used by the website is included in the ZIM, as its MathML is very non-standard.

![image](https://user-images.githubusercontent.com/4304337/172676975-d00ce4f5-9481-473a-8a28-81df44a0ef34.png)
