### ISSUE TITLE
Article stuck at loading

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#166]
ZIM: 2021-03 German Wikipedia
OS: Android 10

This article refrains to load:
https://de.wikipedia.org/wiki/PRISM

https://user-images.githubusercontent.com/71934042/125119251-20628600-e0f1-11eb-8e4e-b48d765444fb.mp4

**Comment by Jaifroid** [comment]
OK thanks, I'll check it out.

**Comment by Jaifroid** [comment]
Thank you, I confirm this bug. The article causes an unhandled exception trying to construct a regular expression that sets up backlinks for endnotes. I'll fix in code, as I can see precisely what is causing the error. I should also add a generic fix to ignore this kind of error in a non-essential function without bombing out.

**Comment by Jaifroid** [comment]
This should now be fixed in the development PWA version `1.4.3-rc4` (the rc4 version must be loaded to see the fix).

**Comment by Jaifroid** [comment]
This fix is now published.
