### ISSUE TITLE
Table of Content is not in its entirety

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#167]
OS: Android 10

The ToC is not outright. Our example is https://en.wikipedia.org/wiki/Charlie_Chaplin

Under "1918-1922: First National" should follow "United Artists, Mildred Harris, and The Kid" and everything elsewise that comes subsequently. These and more are not implicated in the ToC.

Original Kiwix Android app:

![20210710_203559](https://user-images.githubusercontent.com/71934042/125173261-aa2c5500-e1be-11eb-904f-04a330404ca4.jpg)

Kiwix JS PWA:

![Screenshot_20210710-195839_Samsung Internet](https://user-images.githubusercontent.com/71934042/125172594-d3e37d00-e1ba-11eb-887a-80f54a983b94.jpg)

On a side note, this is not the only affected article.

**Comment by Jaifroid** [comment]
@Inbefortus This is because when I first coded ToC, I took the decision to parse only down to `h3`, otherwise the ToC becomes very cluttered in the small space. It only scans `h1`, `h2`, and `h3`, and builds the ToC using those. The titles you list are `h4`.

I think there is a balance between making a usable ToC and a complete one. What do you think? It would be a small code adjustment to add `h4` (but then where do I stop?).

**Comment by Inbefortus** [comment]
@Jaifroid I don't know specifically how that would look on a phone. I use my Tab S7+ with a large screen at all times. Not only that, but I've never really had any complications with the oversight, however I can comprehend that it can look slightly overwhelmed for phone users with a small screen.


If it were up to me, I would say that we should make the ToC complete to optimize navigation and effectiveness of lengthy articles, and if no one agrees with this (potentially involving you), then I would suggest making this configurable through an individual setting. I'm merely thinking of the navigation that is wasted provided we don't adjust this, even if it's only a fraction.

**Comment by Jaifroid** [comment]
I'll include up to `h4`. I think going further than that would be too much, personally. (I'm not sure if headings beyond `h4` exist in Wikipedia archives.)

**Comment by Jaifroid** [comment]
Fixed in Dev PWA v1.4.3-rc5, up to `h4`. Let's see if there's a call for anything smaller. Thanks for the issue: testing it on the Charlie Chaplin article, I think it does improve navigation.

**Comment by Jaifroid** [comment]
This fix is now in the published apps (except the UWP app is still in Certification).
