### ISSUE TITLE
Impossible to open/select a content in the content select box

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#17]
1 - Going to settings
2 - Above "Rescan storage" button, I have what should be a select box with many ZIM files
3 - Each time I click on it it open a content instead of showing me the list.

I have 3 ZIM files on my devices... maybe Kiwix has only one of them and just open it for that reason?!

**Comment by Jaifroid** [comment]
The Rescan Storage button works by scanning the app's own (internal) storage (which cannot be picked using the file or folder picker). It will select whatever is in the app's internal storage, which is probably Ray Charles. If you want to pick a specific and different folder with ZIM files in it, you need to choose "Select folder" which should appear when you tap "Rescan storage". Once you've picked the folder with the ZIM file(s) in it, the app will display whatever is in that folder and has a .zim or .zimaa extension.

If you want to pick a specific unsplit ZIM file (single file), use the other button "Select single archive".

Could you confirm if it's working as described above? NB there is no way to automatically scan your entire SD card -- you have to pick the folder manually unless the ZIM is already packaged along with the app (in this case Ray Charles).

**Comment by kelson42** [comment]
Indeed, work as intend :)
