### ISSUE TITLE
Desktop style not displaying everything

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#170]
When browsing in desktop style, supplemental associated information is not apparitional, although it is generally apparitional on both desktop and mobile style.

Kiwix JS PWA desktop style:

![20210716_203602](https://user-images.githubusercontent.com/71934042/125995588-4d21a888-5d29-4ff2-a5fe-577d3e7e53d2.jpg)

![20210716_203650](https://user-images.githubusercontent.com/71934042/125995592-f57bed71-2e5d-4205-9923-2c0ae43ea4e1.jpg)

Kiwix JS PWA mobile style:

![Screenshot_20210716-202854_Samsung Internet](https://user-images.githubusercontent.com/71934042/125995709-6cf67dd2-ee2a-410c-b10b-b45f46c3a0ac.jpg)

![Screenshot_20210716-203041_Samsung Internet](https://user-images.githubusercontent.com/71934042/125995715-505521a5-0a93-4693-a939-4e9dd5b757d3.jpg)

Original English Wikipedia desktop style:

![Screenshot_20210716-205027_Samsung Internet](https://user-images.githubusercontent.com/71934042/125995771-3c51cc34-3293-403c-851f-962b9b134df7.jpg)

![Screenshot_20210716-205050_Samsung Internet](https://user-images.githubusercontent.com/71934042/125995774-3f92254f-59a6-4a7f-b1cd-83317cb0b9bc.jpg)

**Comment by Jaifroid** [comment]
@Inbefortus I don't see this issue in `wikipedia_en_all_maxi_2021-02.zim` (see screenshot). Which ZIM are you using?

![image](https://user-images.githubusercontent.com/4304337/126070158-400dd924-d681-4b59-9268-2eccf1394671.png)

**Comment by Jaifroid** [comment]
@Inbefortus Are you sure you're not showing screenshots of the Kiwix Android App above? That app has yellow links in dark mode, whereas Kiwix JS PWA has blue links in dark mode (as in my screenshot)...

**Comment by Inbefortus** [comment]
@Jaifroid The ZIM I am using is from 2021-03. 

Yeah. The reason it looks similar is Samsung's high-contrast dark mode.

**Comment by Jaifroid** [comment]
OK, so that would suggest that the issue is to do with mwoffliner not scraping everything in the 2021-03 ZIM, compared to the 2021-02 ZIM. In other words, this issue should be moved to mwoffliner. This is basically the same issue as https://github.com/openzim/mwoffliner/issues/1492, where there was a difference between the 2020-06 German Wikipedia and 2021-03. Clearly something has happened in mwOffliner (or in Parsoid) between 2021-02 and 2021-03. @kelson42?

**Comment by Jaifroid** [comment]
@kelson42 I don't seem to be able to transfer this issue to openzim/mwoffliner (maybe becuase it is not in the Kiwix org repos). But as this issue basically the same as https://github.com/openzim/mwoffliner/issues/1492, it simply adds more proof that either the API has stopped providing some infoboxes, or else (more likely IMHO) there is an issue with mwOffliner that happened between 2021-20 and 2021-03.
