### ISSUE TITLE
Scrolling is no longer possible when clicking on the lens icon

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#177]
OS: Android 10
Browser: Samsung Internet

When you click on the lens icon (search text in the current article), you can no longer scroll efficiently.
You are inevitably forced to restart the app to reverse this, therefore I hardly ever use this crucial and beneficial feature. In the long run, it's irritating to have to restart the app all the time...

Pay attention to the area on the far right:

![20210812_135728](https://user-images.githubusercontent.com/71934042/129192939-83f89b16-b4ef-4208-9cd8-10974e80cf02.gif)

**Comment by Jaifroid** [comment]
@Inbefortus, to summarize in words, the top and bottom bars get "stuck" and no longer "scroll away" after using the title search? I corroborate this behaviour, which should be easy to fix. I think another way to get out of this mode is to go to Config, and toggle the option "Hide toolbars while scrolling". You have to toggle through until it says "Both" again.

Thanks for your report.

**Comment by Jaifroid** [comment]
And just to be precise, it's not that "scrolling is no longer possible": you can still scroll the article, but the top and bottom bars remain on-screen?

**Comment by Inbefortus** [comment]
> And just to be precise, it's not that "scrolling is no longer possible": you can still scroll the article, but the top and bottom bars remain on-screen?

@Jaifroid You are absolutely right. The title doesn't quite match what I meant. I noticed that a short time after publication (I am not able to change the title after publication). I should have been more detailed on the whole. My fault.



> @Inbefortus, to summarize in words, the top and bottom bars get "stuck" and no longer "scroll away" after using the "find-in-article" search? I corroborate this behaviour, which should be easy to fix. I think another way to get out of this mode is to go to Config, and toggle the option "Hide toolbars while scrolling". You have to toggle through until it says "Both" again.
> 
> Thanks for your report.

Here in the video you can see it much better:


https://user-images.githubusercontent.com/71934042/129218038-3811de4c-2f25-440b-be12-50baf81275c1.mp4

Once I click on the lens icon at 00:08, I can't hold the button to scroll up and down.

What you thought is not working is faultless (Hide toolbars while scrolling).

**Comment by Inbefortus** [comment]
@Jaifroid I was wrong. If you click on it without typing or searching for something, it's like this, but if I type something right away, the button reappears. I'm certain it was different in older versions and the button didn't appear again until restart, but that no longer matters:


https://user-images.githubusercontent.com/71934042/129226487-e1285d06-c71d-4f2e-b9eb-8e905574b40d.mp4



Then I guess the matter is settled!

**Comment by Jaifroid** [comment]
I do actually see an issue, but it is different from the one you describe. I'll open a different issue for it.

**Comment by Jaifroid** [comment]
I've added #178 for the issue I've noticed arising from this.
