### ISSUE TITLE
Kiwix JS Windows is now in the Microsoft Store!

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#19]
I'm very pleased that the result of a "long summer" of development is now in the Microsoft Store here:

https://www.microsoft.com/en-gb/store/p/kiwix-js/9p8slz4j979j 

Although this is intended for Windows Mobile, if you have Windows 10 on a tablet or PC, you can test it out without needing a mobile device. Feedback welcome here, or open an issue for the specific bug.

There is already a known bug with "novid" type ZIMs produced in September or October of this year, which will shortly be fixed (kelson already opened an issue for that).

@mossroy @sharun-s

**Comment by mossroy** [comment]
Excellent, that's great news!
All my congratulations for this achievement.

**Comment by sharun-s** [comment]
Take a bow @Jaifroid 👏👏👏 Well done!!!

**Comment by Jaifroid** [comment]
I was interested to find out where it's being used so far!

![image](https://user-images.githubusercontent.com/4304337/33810113-f5832fc4-ddf8-11e7-99bd-bd65a9e05258.png)

**Comment by Jaifroid** [comment]
@Popolechien Would you be able to add the link to the Store version of Kiwix JS to the downloads section of the Kiwix front page (kiwix.org)? The most unobtrusive would be to follow the example of the "Kiwix for Chrome" icon/text, so under the "Kiwix for Windows" icon/text, you could add a second line "or Mobile", with the word Mobile linking to https://www.microsoft.com/en-gb/store/p/kiwix-js/9p8slz4j979j . (Note that it's not Windows Phone, it's Windows Mobile. If you want the link to be more specific it could say "or Windows 10 Mobile".)

**Comment by Popolechien** [comment]
Done!

**Comment by Jaifroid** [comment]
Thank you very much @Popolechien !

**Comment by Jaifroid** [comment]
Update on international usage:
![image](https://user-images.githubusercontent.com/4304337/34817783-d05c8e86-f6b0-11e7-88a5-4bb07ed52ce7.png)

**Comment by Popolechien** [comment]
Re: Mexico and China - do we have localized (e.g. Spanish and Simplified Chinese) interfaces?

**Comment by kelson42** [comment]
@Jaifroid Nice progression :)

**Comment by Jaifroid** [comment]
@Popolechien We don't have any localized versions of Kiwx JS (Windows) yet. It would be a good next move for Kiwix JS (@mossroy ) to think about the best way, technically, to internationalize. I'd rather not go it alone with Kiwix JS Windows, as the method chosen should be common to all Kiwix JS apps.

**Comment by Jaifroid** [comment]
Just cross-referencing to https://github.com/kiwix/kiwix-js/issues/13 (Implement translation of the UI).

**Comment by mossroy** [comment]
I second that. Kiwix-JS is where it should be technically done.
But nobody took the time to work on it so far.
Yesterday, I added the label "good first issue" to kiwix/kiwix-js#13 to (hopefully) encourage some newcomer to work on that. But it's not only a question of choosing a javascript library : we would also need help from some translators

**Comment by Popolechien** [comment]
Well for that part we have translatewiki.net, though I have no idea how it works.

**Comment by kelson42** [comment]
@Popolechien See my answer about that here: https://github.com/kiwix/kiwix-js/issues/13#issuecomment-357220215
