### ISSUE TITLE
Homogeneize screenshots on windows store

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js-windows#20]
Screenshots are both in normal and nightmode, and it is rather disturbing. It would be better to homogeneize the whole thing and present standard view only. I'll put a link on the kiwix.org website as soon as this is done. Thanks.

**Comment by Jaifroid** [comment]
Windows Mobile users are very vocal about wanting a dark mode. They will down-vote apps that don't have it. This is because most Windows Phones use OLED displays where light/white modes are battery drainers. Therefore, I think featuring the dark theme (which is not just for night usage) is important. However, I certainly agree it could be better organized, and I could group all the light mode screen-shots first, followed by the dark mode, so that there is only one transition and not so disorientating. Does that seem like a good compromise?

**Comment by Popolechien** [comment]
Grouping is probably a minimum, yes, so let's go for it, with the caveat that having only one dark mode (with a clear mention "Night mode available") is certainly enough to make the point. Otherwise let's stick to a very conventional presentation: the Welcome, Usage and Configuration screenshots (which are all in night mode) are not very relevant in that regard. Also, rather than the Kiwix article, maybe use a screenshot from the top viewed articles (https://en.wikipedia.org/wiki/Wikipedia:Multiyear_ranking_of_most_viewed_pages#Top-100_list), something non-corporate or non-political, e.g. WWII (# 5) or Michael Jackson (# 6) ?

I haven't/couldn't try it, but do we get mobile view in this app? (i.e. subsections being folded, as in here):

![capture d ecran 2017-11-30 a 12 14 06](https://user-images.githubusercontent.com/21675885/33428210-3f3ea6ea-d5c8-11e7-9eeb-2538548d8393.png)

If yes it would also be a nice thing to show.

Last but not least, you can send me screenshots via email and I can prepare mock-ups like above, which is what we already have on the Android store (https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikimed)

Thanks!

**Comment by Jaifroid** [comment]
For the importance of a "dark mode" to Windows Phone users, see this article that has just (by coincidence) appeared on All About Windows Phone:

http://allaboutwindowsphone.com/features/item/22626_How_to_Read_web_content_in_dar.php

Regarding mobile view, a Table of Contents is implemented at the bottom of the screen. A screenshot is provided on the Microsoft Store:

![image](https://user-images.githubusercontent.com/4304337/33430969-5f2489d2-d5ca-11e7-8235-a925e5336256.png)

I haven't implemented collapsible headings, but this solution seemed a good alternative. There is the possibility of transforming the desktop Wikipedia style to mobile and vice versa, but it's a bit experimental. However, the transformed version from desktop to mobile does not collapse content under headings.

On mock-ups, I haven't found any apps on the Microsoft Store using that style (setting the app content inside a mock mobile phone frame), and the shots have very precise resolution requirements corresponding to the standard size of Windows Mobile screens. This is why such a style is not used as far as I can tell. For an example, compare the most popular Wikipedia app, onePedia: https://www.microsoft.com/en-gb/store/p/onepedia/9nblggh4nb9q -- change the screenshot style from "PC" to "Mobile Device" to see the shot style for Windows Phone. Another example is the official Twitter app: https://www.microsoft.com/en-gb/store/p/twitter/9wzdncrfj140 . They also have a liberal splashing of the dark mode shots... Different store, different culture!

Anyway, I'm happy to group, and to follow recommendations regarding more popular pages. The settings pages were to show off the features available, but it is a bit self-indulgent, so will remove them. I would like to show some language(s) other than English as well.

**Comment by Jaifroid** [comment]
Hi @Popolechien , do you think this presentation of screenshots (for Mobile and for Tablet/PC) is better?

https://www.microsoft.com/en-us/store/p/kiwix-js/9p8slz4j979j 

Switch between Mobile and PC with little dropdown next to "Screenshots".

**Comment by Popolechien** [comment]
Awesome - thanks!
