### ISSUE TITLE
Mouse Buttons BACK & FORWARD Functions Do Not Work.

### ISSUE THREAD

**Issue by washere** [kiwix/kiwix-js-windows#214]
This can be either a Feature Request or Bug or both.

A large percentage of users globally now have mouses with 2 buttons on the side for going back or forward.
Most of these never go back to a mouse without, that is why this large percentage keeps growing. 
Also most professionals from coders to writers to people working daily with computers are only using a mouse with Back/Forward buttons.

Because it saves so much time & is convenient & makes them faster & more productive. They are on many models of wired or wireless (BT, WiFi).
So it is only a matter of time before we have this feature implemented.

Currently the buttons do not work on this release from MS Store.
I tried about 6 different mouse models to test. In my experience once this feature is implemented it works with all mouse models on Windows. Android is another matter, varies on models & OSes. But if you like to do it, it will work with all mouse models with Back/Forward buttons on Windows.

I think after you do it, you will love it yourself and wonder why it was not done before because it is so useful and faster than hunting around the screen for the little icons which is still a bit stone age UI/UX.

Of course Back/Forward mouse buttons  work on Wikipedia etc on all browsers & other Wiki reader apps.

Thanks again for the great work.

**Comment by Jaifroid** [comment]
@washere This is very easy to implement I think (so long as all manufacturers map the mouse back and forward buttons to the same virtual "key" code). It's just a question of trapping those and issuing our own custom back and forward functions (which are essentially history.back() and history.forward() but with a few customizations to ensure content is loaded correctly).

**Comment by washere** [comment]
Thanks Jaifroid.

On Android these buttons work mostly but not always, depends on the OS.
But fortunately all mouse models seem to work on Windows with Back/Forward.
So if the default functions for both are implemented, i am sure they will work with all mouse models.
I think in time majority of mouse models will have these 2 buttons as more people use them and most of them never go back. Because more apps (not just browsers or electron based) are supporting them too.
But it is crucial for wiki based apps anyway to trace history as there is no breadcrumb usually.

Thanks again.

**Comment by Jaifroid** [comment]
I'm pending getting access to a mouse with these buttons in order to do some testing of this. It "should" be easy, so long as the buttons correspond to a trappable mouse event in JavaScript. It didn't work with my trackpad, where a three-finger swipe is supposed to be the equivalent of these buttons. No mousedown, mouseup or click event is registered with these gestures (but I may not be listening on the correct DOM element or contentWindow).

**Comment by washere** [comment]
Thank you.

You might like to do a test build like the other issue for us to test, before your mouse arrives.
I am sure if you declare the 2 procedures globally somewhere appropriate, it will work.
Simply because, once it works on windows, it will always work.

Thanks again for your efforts.

**Comment by Jaifroid** [comment]
I haven't purchased such a mouse, since I use a laptop with trackpad mostly. However, I've now found the X-mouse utility which allows me to simulate the back and forward buttons. I can now reproduce the issue: it works in the Chromium-based PWA version, but not in the UWP version. I can now test my code properly.

**Comment by Jaifroid** [comment]
OK, I've established that I can't detect these buttons in JavaScript, because no mousedown or mouseup event fires for these buttons in the UWP framework. A simple click fires mousedown and mousup events, but not a click with buttons 3 and 4.

This means I would have to fall back to using UWP APIs, if [Windows.UI.Core](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Core?view=winrt-10240) is supported in WinRT's JavaScript implementation.

**Comment by kelson42** [comment]
@Jaifroid Just a friendly wave from here as I remember fighting with this feature request and xulrunner framework more than 10 years ago for Kiwix Desktop 1.0. We have recently introduced this in Kiwix Desktop 2.0 as well... Never ending topic looks like :)

**Comment by Jaifroid** [comment]
@kelson42 Ha! Plus ça change... 🙂

**Comment by Jaifroid** [comment]
@washere Good news: while mousedown events don't fire, I've discovered that the standard JS `pointerdown` event does fire. This means I can now detect these buttons and process them.

**Comment by Jaifroid** [comment]
@washere Please see https://github.com/kiwix/kiwix-js-windows/releases/tag/v1.8.12-dev for a test package which I think fixes this issue.

**Comment by washere** [comment]
Hi Jaifroid,

Just got home and saw and installed this.
Testing for about 10 minutes till this minute.
Works perfect, back and forth in all levels. Not that it matters, once it goes back/forth, levels are irrelevant.

Also works in settings and goes back to homepage.
And it keeps settings that were changed (for example switch to dark mode etc) in settings, so that's cool too that the old code recognizes to keep changes when going back by any means.

The external monitor bug is present in this test build but i guess you know that.
Would be fantastic to have a release that fixes that bug and has this back/forth too.
I think the issue is addressed brilliantly and you could close this issue whenever you want.

I wish more devs were as capable and fast and responsive to users as you, not to mention a very nice person.

THANKS VERY MUCH bro, have a great weekend.
Best wishes.

**Comment by Jaifroid** [comment]
Thanks @washere. I'm just preparing a Store release that will have both of these fixes.

**Comment by washere** [comment]
Thanks, looking forward.

Some Logitech mouse models work with their software called "Options".
It allows to assign many things such as buttons to do different things in different applications, good for coders and graphics workers. Detects current app & switches functions for buttons.

Options has a section called "FLOW".
This allows the mouse to go across computers. So you go to far edge and then it pops up on another laptop.
It even works across Windows & Macs. Android support is promised for flow.
Not all mouse models are multi computer enabled.
Most of these do bluetooth + Dongle (WiFi). With a button to switch modes.
Very few mouse have Dongle (Wifi) + 2 bluetooth connections.

You can arrange 2 computers positions in Flow settings like in Windows settings: dragging 1 & 2 monitors around each other.
So can go left or right or top or bottom for mouse to go second computer.
Also can set 2nd option requiring CTRL key pressed too for mouse to go beyond edge to next computer or just stop at border.

Logitech's most popular pricey model is MX Master 3, about a hundred dollars/euros. Currently on sale in Amazon italy, but returns to italy can be problem, so hope for a good one. Of course MX 3 has Options/Flow. Most logitech models do not have it.

I prefer Logitech M590, because unlike all mouse models, the button to switch between 2 computers is on top, not under the mouse. So i can switch from Windows laptop to android tablet (Flow not working on android yet) or chromebook. Switch fast without turning mouse over for switch at bottom like almost all multi-mode mouse models. Also it about a third of MX 3 (about 30 dollars/euros) and also works with Options/Flow. Often on sale on amazon for 20.

Can set amazon price drop alerts on camelcamel for whatever country for both M590 & MX Master 3, to send price drop alerts, i have several items alerts sent to a secondary email account of mine. camelcamel do not spam or share emails, alerts can be deleted fast too.

With Flow you can use the mouse to also copy/paste files across 2 computers (Windows & Macs too), have to be on same wifi.

This post for anyone who comes across this post, in the closed issues section. Some links for Flow models:


https://www.logitech.com/en-gb/product/options/page/flow-multi-device-control
https://support.logi.com/hc/en-us/articles/360023188134-Logitech-Flow

List of models that have Options/Flow:
https://www.logitech.com/en-gb/product/options

Videos on Flow or key assigns per app etc:
https://www.youtube.com/results?search_query=logitech+flow+multi

**Comment by washere** [comment]
Thanks @Jaifroid 
just updated via winget and both issues working well now.
Thanks again.

**Comment by Jaifroid** [comment]
@washere Thanks for all the testing. Real-world reports like yours really help to improve the app. Regarding the package you now have, are you sure winget gave you version 1.8.2? And also, if you didn't uninstall the previous test package first you might still have that one. Winget should now be serving the updated package that has both fixes. See thumbprint info below, which you can see by typing `winget show kiwix.kiwixjs` (but that will show the package it is serving, not necessarily what you have installed).

I'd recommend waiting a few hours (can be 24-48 hours) for the MS Store version, because that's the one that updates itself in the future. I'm not 100% sure how winget handles updates, but I think you have to do `winget upgrade xxxxx`. The packages are the same, except that the winget one is signed with the Kiwix org code-signing certificate, and the MS Store one is signed by MS.

Before updating from the Store, uninstall any existing UWP version. The Store's info page will show v1.8.2 and a date of 5-Dec-21 once the latest package has passed certification.

```
Installer:
  Type: Msix
  Download Url: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.8.2/KiwixWebApp_1.8.2.0_AnyCPU.appxbundle
  SHA256: cc26824a466ba28e986ab1be6af59d32a05a9cf3b01d2db20e6663b447275d39
```

**Comment by washere** [comment]
Hi buddy,
Thanks for the tips & info too.
Just got home & saw this. I installed & uninstalled the winget version last night. 
I just reinstalled it. Version by -show or -list  parameters show correctly as v1.8.2.0

> C:\Users\User\Desktop>winget show kiwix.kiwixjs
Found Kiwix JS [Kiwix.KiwixJS]
Version: 1.8.2.0
Publisher: Kiwix
Moniker: kiwix
Description: Kiwix is an offline reader for content from Wikipedia, Project Gutenberg, TED Talks, Wikivoyage, Stackexchange, etc. It makes knowledge available to people with limited or no Internet access. The software as well as the content is free to use for anyone. It requires an offline ZIM archive (can be downloaded in the app).
Licence: GPL3
Licence Url: https://github.com/kiwix/kiwix-js-windows/blob/master/LICENSE
Installer:
  Type: Msix
  Download Url: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.8.2/KiwixWebApp_1.8.2.0_AnyCPU.appxbundle
  SHA256: cc26824a466ba28e986ab1be6af59d32a05a9cf3b01d2db20e6663b447275d39

Both issues now seem fixed: no resize bug + mouse forward/back buttons work.
Might be github repo file was not yet updated when i installed last night.

I also just tested the store version and you are right, still the old version. 
I will wait a few days for that, as i am sure you will have to check a few things before uploading there.
That will be my main version due to self_upgrade feature. But good to know the winget upgrade param too, thanks.

I also just downloaded the latest portable Electron version for Win10.
My previous portable was v1.7.7E. 
The new one is, kiwix_js_windows-1.8.2N-win-ia32.

Couple of wishlist features for official MS Store/Winget version would be:
On relaunch load the last page on app exit
Some bookmarks feature

I understand  that Bookmarks or any new feature would need to be agreed by all devs for all platforms though, whatever that process is. But would be nice for serious work.

I will keep testing and report back.

Thanks very much for all the great work,
Have a great week.

**Comment by Jaifroid** [comment]
The Store version is in certification. We just have to wait for MS to review it, then they'll release.

The UWP (Store/Winget) version should remember the last visited page, unless you turn that option off in Config. There is a small bug, however. Often the first page visited after the landing page doesn't get remembered if you exit straight after. If you browse a couple of pages, you should find that the page is remembered and it is restored when you re-open the app.

I'll make an issue for this small bug.

Bookmarking is also on my wish list, but is complicated to implement. Browsers provide this feature natively, but the HTML frameworks / browser engines often don't expose that functionality. So it would have to be emulated...

Thanks for suggestions.

**Comment by Jaifroid** [comment]
See #218.

**Comment by washere** [comment]
Thanks buddy, will read that.

The resize bug is happening about half the time with a big file i just set as default to load on launch:

**wiktionary_en_all_maxi_2021-10.zim**

It is just over 6 gb (6.01 GB (6,455,477,137 bytes)). I downloaded it last week with Qbittorrent app.
I posted here since you just commented. I will test more and post next week in the correct thread.

I think because it's homepage is fairly wide depending on 2nd monitor for relaunch (external on mine), is why it happens.
It happens about 30% of relaunches. The last exit should have been not maximized screen for the bug to recur.

I think this bug happens more with long text lines and no images on homepage of ZIM file.
I thought to let you know. Will post in the correct issue thread next week if i get anything more to report.

Thanks again.

**Comment by washere** [comment]
Apart from config online rep, the file:

wiktionary_en_all_maxi_2021-10.zim

can also be found in:

https://ftp.nluug.nl/kiwix/zim/wiktionary/

The smaller dictionary files (_en) English language versions might replicate the bug, specially nopic versions.

**Comment by Jaifroid** [comment]
I've downloaded this, but can't reproduce the issue. NB size of ZIM archive is immaterial. I usually work with the 90GB full English Wikipedia. We don't read the whole file into memory, only the slice we need for a specific article. Could you make any further discussion of a possible regression on a new issue, please? Thanks!

**Comment by washere** [comment]
Hi,
Please see Reply in relevant thread:

https://github.com/kiwix/kiwix-js-windows/issues/213
