### ISSUE TITLE
Succession boxes hidden?

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#222]
I have already created a ticket for this at MWOffliner https://github.com/openzim/mwoffliner/issues/1514

The reason I'm making a new post here is because I'm wondering if succession boxes are actually included in the ZIM file, and you can display them with some code.

@Jaifroid When you introduced the "Display hidden block elements" option, things popped up that would never have popped up without that particular option.

Example:

Disabled:

![20211225_154713](https://user-images.githubusercontent.com/71934042/147387583-f12256ce-7478-4d3f-a88d-30b850401baa.jpg)

Enabled:

![Screenshot_20211225-154734_Samsung Internet](https://user-images.githubusercontent.com/71934042/147387567-f6b36afd-ed8b-48dd-9b7a-965dece56050.jpg)

Empty succession box:

![20211225_153220](https://user-images.githubusercontent.com/71934042/147387680-91e4d1b3-bf87-495b-9f62-e6eb00ddfd43.jpg)

I wonder if you can determine if these are entirely excluded from scraping and if not you can somehow get them to display. It would be pleasant if this was not the case, and you could display them through a new option, since they are considerably valuable.

**Comment by Inbefortus** [comment]
@Jaifroid Perhaps there is a connection here https://github.com/openzim/mwoffliner/issues/1558#issuecomment-1001029021

**Comment by Jaifroid** [comment]
@Inbefortus If you can tell me which article and which ZIM, I can check the source code of the article to see if the information is merely hidden or is in fact absent.

**Comment by Inbefortus** [comment]
@Jaifroid https://en.wikipedia.org/wiki/Arthur_Wellesley,_1st_Duke_of_Wellington 
Has the most I have seen.

**Comment by Inbefortus** [comment]
@Jaifroid Don't waste your time. Unfortunately, they are completely excluded from scraping because `wikitable succession-box` has changed to `wikitable succession-box noprint`, which MWOffliner cannot scrape because of `noprint`.
- https://github.com/openzim/mwoffliner/issues/1495#issuecomment-883309121

**Comment by Jaifroid** [comment]
Ah OK, thanks for letting me know.
