### ISSUE TITLE
Add a favicon for Kiwix JS PWA

### ISSUE THREAD

**Issue by xmha97** [kiwix/kiwix-js-windows#229]
Please add a favicon for Kiwix JS PWA
![image](https://user-images.githubusercontent.com/23485114/150629760-0d3e92ea-15c2-4791-9083-f28511375679.png)

**Comment by Jaifroid** [comment]
Thanks for the suggestion.

**Comment by Jaifroid** [comment]
This is fixed in master, and will be in the next release.
