### ISSUE TITLE
Remove drop-down indicator if only one archive is found

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#23]
When only one archive is found in storage, the drop-down indicator is still displayed:

![image](https://user-images.githubusercontent.com/4304337/33522976-a3807972-d7f2-11e7-8a2f-13603249df20.png)

This is confusing, because it leads the user to click on it looking for more archives, but clicking on it opens the archive. Ideally also add a number in the description saying how many archives have been found.

**Comment by kelson42** [comment]
Yes, I confirm :)

**Comment by Jaifroid** [comment]
Commit https://github.com/kiwix/kiwix-js-windows/commit/bc210055efce33ead44cfa43a6f3e744d4aafbc6 removes the caret. I have also renamed "Rescan storage" to "Select storage", as I think "Rescan..." misleads user into thinking that the whole device will be scanned for archives (which is not possible afaik in UWP, and in any case could take far too long on some devices with many files and folders):

One archive found:
![image](https://user-images.githubusercontent.com/4304337/33523914-f55b3716-d809-11e7-8fd8-b0da4673f0d1.png)

Multiple archives found in user-selected folder:
![image](https://user-images.githubusercontent.com/4304337/33523929-83d09a72-d80a-11e7-93d4-a89fdca523c9.png)

**Comment by Jaifroid** [comment]
Commit https://github.com/kiwix/kiwix-js-windows/commit/ece6cc0dcd43323e320f132bfeb6415581794f5e adds some more intelligent dynamic code for dealing with this caret, as it turns out that the previous fix was preventing selection of a specific ZIM when the user has picked a folder containing several ZIM archives. Therefore the new code removes the "multiple" attribute if there is more than one ZIM archive available, and puts it back in if there is only one. Fix tested in several scenarios, and this fix is incorporated into release [0.9.3.0 Beta](https://github.com/kiwix/kiwix-js-windows/tree/master/AppPackages/KiwixWebApp_0.9.3.0_Test).
