### ISSUE TITLE
Create custom apps with preloaded content

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#24]
This is the same enhancement issue as discussed on Kiwix JS: https://github.com/kiwix/kiwix-js/issues/292

Having released a beta of the main app for Kiwix JS Windows, I would be keen to implement a custom version of Kiwix JS Wikivoyage for UWP. Since the app has been designed to open the first ZIM it finds in its internal storage folder automatically (this is currently Ray Charles, just so we don't ship a completely empty and "useless" app for a naïve end-user), it would be trivial to replace Ray Charles with Wikivoyage.

I'd appreciate advice and policy on this from @kelson42 . I understand these standalone versions have been very popular on Android. Wikivoyage is the most obvious use case for an offline ZIM reader for travellers who may find themselves regularly without an Internet connection. The ZIM is also not too large for the English-language version, currently ~700Mb.

There is also a very compelling use-case for Kiwix JS Wikimedicine, but the English language file with pictures is 1Gb, so it might make sense to start with the smaller Wkivoyage file, to troubleshoot download and storage issues.

I think there is also an argument that having more apps increases discoverability and helps to spread the Kiwix technology by making people aware of it.

**Comment by Jaifroid** [comment]
@kelson42 @mossroy What app name should I choose for the Windows Store Wikivoyage version?

* Kiwix Wikivoyage
* Kiwix JS Wikivoyage
* Wikivoyage JS
* Something else?

I can't use just "Wikivoyage" because someone has taken it for a Web app (that app accesses the Wikivoyage website online and formats it for mobile view in the app -- doesn't use a ZIM file).

As I'm sure you know, here is the equivalent page on the Play store:

https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikivoyage

**Comment by mossroy** [comment]
Maybe "Kiwix Wikivoyage" would be enough, but @kelson42 is probably more adequate to give an answer.

**Comment by kelson42** [comment]
@Popolechien ?

**Comment by Popolechien** [comment]
Wikivoyage offline travel guide is the name we use, and it has all the keywords needed for a search - if you want to start building brand recognition for Kiwix then "Offline Wikivoyage - powered by Kiwix" would be the choice (though I find it too long and would keep it for the description text).

**Comment by Jaifroid** [comment]
Thank you, all. Someone already has "Wikivoyage Offline" (but no app under that name, it's probably reserved by the people who made "Offline Wiki", an x86-only app in the store) and "Wikivoyage Offline Travel Guide" is too long to fit on the medium-sized tile (MS recommends title lengths that will fit, which generally means no more than three words, ideally one of those quite short).

"Wikivoyage JS" is available, mirroring "Kiwix JS" (we chose to add "JS" to "Kiwix" to distinguish it from the x86 app, as a signal that this is a JavaScript-based app to those in the know, and unobtrusive to those majority who have know clue what JS signifies).

"Kiwix Wikivoyage" is also available. If preferable we could probably also do "Wikivoyage by Kiwix". We can add keywords and a description including terms such as "travel", "offline", "guide", etc., to any of these titles.

So I think the choice boils down to:

* Kiwix Wikivoyage
* Wikivoyage JS
* Wikivoyage by Kiwix

I've pre-emptively reserved these three. Any strong views amongst these? Or feel free to suggest something else that is probably no more than three shortish words.

**Comment by Popolechien** [comment]
Mild preference for the third one, if only to avoid future discussions with the Foundation's legal team (from past discussions I remember they favoured us using a distinguishing/separative name for apps using their trademarks)

**Comment by Jaifroid** [comment]
Seems like a good reason. I'll go for the "Wikivoyage by Kiwix" unless I hear anything to the contrary by tomorrow!
