### ISSUE TITLE
Links in Stackexchange ZIMs are not working

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#26]
Pre-alpha support was added for Stackexchange ZIMs (appropriate stylesheets to make the text at least readable), but links are broken. You can search for the text of the link and successfully open it, but the link itself does not work. The fact that search works means this is probably relatively easy to fix.

**Comment by mossroy** [comment]
This is probably the same issue as https://github.com/kiwix/kiwix-js/issues/205
The jQuery mode forces us to try to "recognize" links in the HTML string with regular expressions. And we probably made some assumptions with the structure of wikimedia ZIM files.

**Comment by Jaifroid** [comment]
Yes, this looks like the same issue, and I'd be happy to work on it upstream in Kiwix JS, as it's in fact also quite similar (I think) to the workaround implemented for #18 : https://github.com/kiwix/kiwix-js-windows/commit/b9c8f87ba8cf9970e31cc9fc7ece0393a81453c4 . It'll probably be one of the Regexes referenced in that snippet.

**Comment by mossroy** [comment]
That would be cool, indeed, to have a Pull Request on kiwix-js if you find a proper way to handle those links

**Comment by Jaifroid** [comment]
Kiwix JS now handles these properly, so I need to transfer the code from there, as I currently have a workaround rather than the complete solution in this repo. TODO.

**Comment by Jaifroid** [comment]
Commit https://github.com/kiwix/kiwix-js-windows/commit/447b7442ccc2c64013b90fbabbbfea27273a45e7 has now ported the revised code for subdirectories from Kiwix JS to Kiwix JS Windows. Seems to be working well. Will test a bit more to be sure before closing this.
