### ISSUE TITLE
ZIM downloads from mirrorservice and fau.de attempt to download the ZIM as plain text and display in browser

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#28]
This affects Edge and IE, but not Firefox, hence it affects Windows Mobile because it uses the Edge engine (and no way to change that). Other download servers correctly offer to download the file.

I'm reporting the issue to the server providers. However for now it's important to work around it -- this is done for mirrorservice (the app recognizes it and prevents the link from being clickable), but not yet for ftp.fau.de, so this needs to be added to the workaround. 

NB this is not a bug in the app. It's either a bug in Edge and IE or it's a bug in the two servers.

**Comment by kelson42** [comment]
I suspect it is not easy to solve the problem on your end. The only solution I see is inviting the users to make a right-click (whatever that is possible on mobile devices) to then click "save as" in the contextual menu. 

That said, I have written an email to both mirrorservice and fau webmaster to ask them if they could add the HTTP response header `Content-Type: application/octet-stream` to ZIM requests.

Hope they will do it and that this will be enough to force IE to avoid opening the ZIM file with the HTML browser.

**Comment by rrzefox** [comment]
At ftp.fau.de we have now added
```AddType application/octet-stream .zim .ZIM```
to the Apache config. Previously, no content-type-header was sent at all for ZIM files.

**Comment by Jaifroid** [comment]
@rrzefox Great-- I can confirm that download of ZIMs is now working for ftp.fau.de in Edge, and hence in Kiwix JS UWP. Thank you for speedy response on this.

**Comment by kelson42** [comment]
Mirrorservice has also added the the `application/octet-stream`. This bug should be therefore fixed now.

**Comment by Jaifroid** [comment]
Excellent - yes, this seems to be fixed according to my test of it just now. Thank you very much @kelson42 .

I'll leave this open a bit longer as a reminder to me to removed the workaround that I put in Kiwix-JS-Windows.

**Comment by Jaifroid** [comment]
Commit https://github.com/kiwix/kiwix-js-windows/commit/f050db102f2d9f4460d2a92e48884d4768438ce0 comments out the workaround.
Closing.
