### ISSUE TITLE
On Ubuntu with Chromium installed via Snap, starting the PWA from the desktop icon displays empty window

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js-windows#284]
The PWA can be installed, and generates a new icon on the user desktop.
It has to be manually set as executable, and can be started afterwards.

However, instead of opening kiwix-js-windows, it opens an empty chromium window (like if I simply opened a new instance of Chromium)

**Comment by mossroy** [comment]
Tested on Ubuntu 20.04 and 22.04

**Comment by Jaifroid** [comment]
Hmm. This sounds like a bug in the API. Again, I don't do anything special to generate the installation. It is entirely handled by the browser. The only thing that I do is show a button when the browser fires the `onbeforeinstallation` event (that may not be exactly what the event is called, but it's similar). Then, when the user clicks the button, the browser detects that the user wants to install and does the rest.

I've labelled this as "upstream" not to indicate that it should be worked on in Kiwix JS, but that it may need to be reported to Chromium.

I'll try to reproduce.

**Comment by Jaifroid** [comment]
I've found some posts referring to this issue. Seems to be related to the snap sandbox, as all reports relate to the snap version:

* https://askubuntu.com/questions/1233058/chromium-snap-on-ubuntu-20-04-some-webapp-shortcuts-not-working-workaround
* https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1732482

The second one '[snap] doesn't properly save desktop files for "create shortcuts" action' is probably the best place to report this, albeit specifying that it also affects PWA installation.

**Comment by Jaifroid** [comment]
For a partial solution, it seems you need to edit the .desktop file. See https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1732482/comments/28 .

**Comment by Jaifroid** [comment]
This upstream issue is beyond my control.
