### ISSUE TITLE
Add "CHANGELOG" file to the git repo

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#29]
Like here for Kiwix Android: https://github.com/kiwix/kiwix-android/blob/master/CHANGELOG

This is quite helpful to follow what has been improved in which version ... and to properly communicate around them.

**Comment by kelson42** [comment]
Oops... duplicate of #12

**Comment by Jaifroid** [comment]
@kelson42 I've now added a changelog. Currently it just shows changes for the two public releases to the Store. In future will show changes for interim releases/fixes here on GitHub.
