### ISSUE TITLE
App sometimes force closes while file picker is open

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#3]
I suspect this is also a memory issue. App appears to WM10 to be a single html page, but then starts initializing memory heaps in the background?

Perhaps minifying some libraries for release will help lower the footprint. Or else find a way to increase declared memory requirement for the app.

**Comment by mossroy** [comment]
If no ZIM file has been selected before, there's not reason why it would start working in the background and start eating some memory.
I'm not sure minifying would help : it would influence the size of .js files, not the amount of memory they consume when running.
It would be worth having some debug info on why it actually closes

**Comment by Jaifroid** [comment]
Yes, this one is puzzling me. It's inconsistent and again only happens on the phone, not on desktop UWP app. I'll try to get some debug data, but since it's WM10-specific, I'm thinking maybe the best fix would be (for this specific app) to use the UWP native file-picker API, as this will allow the app to pick a directory and remember its usage rights to the directory, mimicking the functionality you ( @mossroy ) implemented in abstractFileSystemAccess for Firefox OS.

**Comment by Jaifroid** [comment]
@kelson42 , I believe you experienced this bug when testing on your testing device (you mentioned a ZIM file crashing the app, but I believe it was this FilePicker bug, correct me if wrong).

There is some info about this bug on [msdn](https://social.msdn.microsoft.com/Forums/en-US/13002ba6-6e59-47b8-a746-c05525953c5a/uwpfileopenpicker-bugs-in-win-10-mobile-when-not-debugging?forum=wpdevelop). Summary: In a testing environment, when the app is attached to a debugger, it does not close while the user is picking a file. However, when installed on the physical device, on opening the file picker the system sees the app as "suspended" (it is technically not running). The system sometimes therefore closes the "suspended" app as part of its memory management.

The immediate workaround is to choose the ZIM file quickly, before the timeout... Only acceptable during testing, of course. Other workarounds are: 1. to use the native API for opening the file, which has resume methods; 2. declaring the app as a target for saving any kind of file, or 3. declaring it as a target from which other apps can open a ZIM file. I will try 2., 3., then 1, and will update.

**Comment by Jaifroid** [comment]
On initial testing, release 0.7.6.0 has not force-closed on me during file picking. This release contains solution 2. Counter-intuitively, this registers the app as a "file save picker", making it available as a save location for other apps. It seems this keeps the app open for longer while suspended, waiting to receive files from other apps. (This may have negative effects on other apps if they try to save to this app -- needs testing.)

**Comment by Jaifroid** [comment]
Using the native filepicker and folderpicker APIs, as of #4 , seems to have solved this issue. Tentatively closing.
