### ISSUE TITLE
Testing Wikivoyage pre-release package

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#30]
@kelson42 I've made an initial pre-release package for the "Wikivoyage by Kiwix" app:

https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.4-Wikivoyage 

Installation instructions are on that page, especially with regard to checking space requirements -- I'm guessing you'll need at least 2Gb free on the mobile device -- to store the appxbundle, to decompress it, and for the app itself.

If you are able to test it on your test phone, that would be very helpful. I've just tested it on mine, and it installs and runs fine, and basically behaves just like Kiwix JS, only it has the Wikivoyage ZIM packaged in place of Ray Charles. The version of the ZIM package is displayed on the Information page (top right button of toolbar).  I will add below some observations I have from testing it on my 950XL.

**Comment by Jaifroid** [comment]
I note that the visual assets for Wikivoyage are very small on the phone. Because the writing inside the icon is greyish rather than black, it tends to get lost, especially on the smallest icons.

I could edit the icon to make the writing black, which would help on the pinned transparent tile (if the app is pinned to the front screen), and perhaps with the mini icon appearing on the toolbar.

The mini icon on the toolbar occasionally changes back to the Kiwix icon incorrectly, even when the Wikivoyage ZIM is still loaded. The icon swapping code for the ZIM file needs checking.

Other than that, everything runs as per Kiwix JS on a Lumia 950XL.

**Comment by Jaifroid** [comment]
I've re-rendered the smaller icon, and I think this is now more legible (icon top left below). Still experimenting with Live Tile icons, as the "wiki voyage" text may be better as white where the tile is transparent.

![image](https://user-images.githubusercontent.com/4304337/33930967-916a430c-dfe6-11e7-855c-42d550bd5f98.png)

**Comment by kelson42** [comment]
Big difficulties to download it (errors)... but It seems I achieved... but I have an error at install time.

**Comment by Jaifroid** [comment]
Sorry about the download difficulties... Do you have enough space on the phone? Are apps set to install to the SD card or to the main storage?

**Comment by Jaifroid** [comment]
PS If the download is corrupt, I could put up a new package with the changes since I posted that one. (Changes are minor or cosmetic, but they do include opening of last-visited page.)

**Comment by kelson42** [comment]
It looks like, that even with error, the app has been installed on the device and seems to work properly.

**Comment by kelson42** [comment]
One bug: it looks like the external links do not display properly the icon? So it is impossible to make the difference between internal and external links.

**Comment by Jaifroid** [comment]
Thanks for that bug report, @kelson42 . I've opened issue #32 to deal with it.
