### ISSUE TITLE
Publish 64-bit version for Windows

### ISSUE THREAD

**Issue by xmha97** [kiwix/kiwix-js-windows#303]
Hi, Please publish 64-bit version for Windows.
![image](https://user-images.githubusercontent.com/23485114/194703762-7213ceea-9431-4aec-a774-7769d44aa3b0.png)

**Comment by Jaifroid** [comment]
@xmha97 The 32bit one runs exactly the same speed as the 64bit, so I don't see the advantage of building 64bit. It could just create unnecessary confusion for users about which one to pick. The 32bit runs fine on 32bit and 64bit Windows, whereas the 64bit one doesn't run on older 32bit systems.

**Comment by Jaifroid** [comment]
Since I have not heard a good reason why a 64bit version is necessary for Windows, I'm closing this
