### ISSUE TITLE
Maps of POIs are not displayed in Wikivoyage ZIMs

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#31]
Comparing the article for Kalamata (Greece) from `wikivoyage_en_all_novid_2017-12.zim` to the online version of the page (screenshot), the map you see there is completely missing in the ZIM.

While I understand that the best solution would be to use the device's mapping APIs to show a map with the Points of Interest, that is very complicated...

@kelson42 Is there any possibility that mwoffliner could scrape what is displayed visually in the browser on first opening the page? I imagine it's not so easy, as there is no actual fallback image. No API for getting the map render as an image?

![image](https://user-images.githubusercontent.com/4304337/34072716-55b51ecc-e284-11e7-8438-2471e4e3c7e3.png)

**Comment by kelson42** [comment]
This works with a third party web backend. That is why there is nothing IMO we can do shortly to fix this. To me this is related to the general challenge of embedding maps and geo tools to ZIM. This is seomthing I want to start to work on this Q3/Q4 2018.

**Comment by Jaifroid** [comment]
OK, thanks, good to know this is on the longer-term horizon! In the meantime, I can make the POI links open the device's own mapping app (as a separate instance) and show the pointer to the location on the map (which may or may not be available offline). Not quite the same as having an overview map with various POIs in relation to each other, but still useful.

**Comment by kelson42** [comment]
@Jaifroid Can you please post the (POI) link you are talking about?

**Comment by Jaifroid** [comment]
I mean the links in Wikivoyage that look like: `geo:37.04741,22.11429`, which are part of the vCard specification. I can add a small bit of JavaScript in the app that makes these links open in the mapping app on the device. At the moment they don't do anything on Kiwix-JS(-Windows), or on some devices they will throw an alert message saying the page can't be found.

While I'm at it, might as well do "tel:+331456765432" links as well, so clicking on telephone links will open a dialler.

**Comment by kelson42** [comment]
@Jaifroid OK, I fully misunderstood your ticket first. So, here there is nothing to do on mwoffliner/Zim side. This kind of links `geo://` or `tel://` are here on purpose and indeed they are thought to be handle by third party apps. So, yes, kiwix-js-windows should allow that opening through third party apps.

**Comment by Jaifroid** [comment]
I agree that opening such *links* should definitely be handled by third-party apps, but if it were possible, it would be great for the ZIM to have a rendered overview map (not interactive, just an image) like the Kalamata one with all the POIs shown, within the article. It's what people see when they use the online version of Wikivoyage, so they may expect to see it in the offline version. Definitely helps to see that the hotel I want to stay at is a long way from the bus station, etc.

I completely understand this would be longer term, if it is possible at all.

**Comment by kelson42** [comment]
@Jaifroid Yes, but this is another problem (like explained in a previous comment). So it seems one part of your ticket is OK (from ZIM point of view)... and not the other part.

**Comment by Jaifroid** [comment]
OK, so the best I can manage is to drop a map marker on Wikivoyage geo: tags, and link it to the mapping app. The [Wikivoyage branch](https://github.com/kiwix/kiwix-js-windows/tree/Kiwix-JS-Wikivoyage) should now produce a display as below when there are geo: tags. Hovering over a map marker icon will display "Show this place on a map". Tapping will open the built-in "Maps" app and show a map of the area with location marker and the name of the place (bottom screenshot). If the map is available offline, this will work entirely offline.

The specific code here is for Windows 10 (Mobile) and the built-in mapping app, but a similar approach should work with, say, an Open Street Map app on other platforms (Open Street Maps has offline maps).

![image](https://user-images.githubusercontent.com/4304337/34116285-1065877a-e410-11e7-9a68-fd67f91eac08.png)

This is the map that opens when tapping one of the map markers:

![image](https://user-images.githubusercontent.com/4304337/34116339-3b242c14-e410-11e7-8997-646bfd3c9ca4.png)

**Comment by Jaifroid** [comment]
These changes have now been pushed to [Release 0.9.6 beta](https://github.com/kiwix/kiwix-js-windows/releases), so closing.
