### ISSUE TITLE
UWP consistently crashing when jumping to SW mode if anything other than the packaged ZIM is loaded

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#316]
Another regression. Grrr.

**Comment by Jaifroid** [comment]
Fixed in master. Awaiting publication of next version to close.

**Comment by kelson42** [comment]
> Awaiting publication of next version to close.

This is slightly unusual. Usually tickets are closed when fixed, independently of the release mgmt/date. May I ask why you want to keep the ticket open?

**Comment by Jaifroid** [comment]
> This is slightly unusual. Usually tickets are closed when fixed, independently of the release mgmt/date. May I ask why you want to keep the ticket open?

Well, I think a user who notices a problem might come to this repo to report the issue, and might not think to check for closed issues. So in general, I prefer to keep an issue open until the release that fixes it is published, but label with 'fixed'. I realize it's not the usual way, though I have seen some devs doing so. In any case, a new version is in progress, just awaiting publication in Stores.

**Comment by Jaifroid** [comment]
Fix is now in v2.2.5, which has been published.
