### ISSUE TITLE
Publish the 64-bit version for Windows

### ISSUE THREAD

**Issue by xmha97** [kiwix/kiwix-js-windows#328]
Please publish the 64-bit version for Windows.

Currently, there is only a 32-bit version:

![image](https://user-images.githubusercontent.com/23485114/207998517-e9af0e2b-be6c-48bf-9b34-3357c35fd9b5.png)

Thanks.

**Comment by Jaifroid** [comment]
@xmha97 There is no advantage of a 64-bit version for Windows. The 32bit version runs at exactly the same speed on a 64-bit system (I've tested a number of times). By publishing a universal version for Windows Electron, I reduce confusion, proliferation of links and archives, and download/upload bandwidth.

I would need a compelling reason why a 64-bit version would be a benefit to users before adding this as a new target. I think a higher priority is ARM and getting the Electron app distributed via the Microsoft Store.

**Comment by Jaifroid** [comment]
As no rationale has been provided, I'm closing this.
