### ISSUE TITLE
"Wikivoyage by Kiwix" now in Microsoft Store

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#34]
Following on from issue #24, there is now a version of Kiwix JS Windows packaged with the December 2017 English-language Wikivoyage ZIM in the Microsoft Store, available from here:

https://www.microsoft.com/en-gb/store/p/wikivoyage-by-kiwix/9n5sb90q4jbj 

As it is a UWP app, it requires Windows 10 (Mobile / Tablet / PC). It can also be sideloaded from the Releases tab of this GitHub: https://github.com/kiwix/kiwix-js-windows/releases. It is a large download (nearly 700Mb) and may need double this space for installation. I have recommended at least 2Gb free space and installation on a microSD card (in the case of Mobile, obviously). Uninstall any previous test version before attempting to install from the Store. Installation from the Store has been tested on a Lumia 950XL and a Surface tablet, with no hitches.

I'm opening this issue to gather any feedback on this package, its Store presentation, any download or installation difficulties, etc.

One minor issue is #32 - this package does not display the icon that distinguishes external links from internal ones when using locally cached stylesheets. This stylesheet issue has been corrected in the current [Wikivoyage branch](https://github.com/kiwix/kiwix-js-windows/tree/Kiwix-JS-Wikivoyage) but will not get into the Store until the next packaged release. It can he worked around by turning off the use of locally cached stylesheets in the settings.

**Comment by kelson42** [comment]
@Jaifroid I have tested it and for me it seems to work well. I think the problem of missing icon to display next to external links, because it has been fixed, is important enought to make an update of the whole app. An other point I remarked is that the icon of the bottom bar are not centered properly... but I suspect you already know that. All in one, again, a really good job! Congratulations :)

**Comment by Jaifroid** [comment]
Thank you @kelson42 . Will do an update shortly. I still need some investigation about what is going wrong with the bottom bar on smaller displays. It's a bit temperamental: sometimes it all looks fine, and then suddenly the icons all bunch up... Will keep investigating.

**Comment by Jaifroid** [comment]
@kelson42 We got a good review of "Wikivoyage by Kiwix" here:

http://allaboutwindowsphone.com/flow/item/22691_Mini-review_Wikivoyage_by_Kiwi.php

**Comment by mossroy** [comment]
Congratulations!

**Comment by Jaifroid** [comment]
Version 0.9.7 (beta) of Wikivoyage by Kiwix, with the January 2018 Wikivoyage ZIM, is now downloadable from the [Microsoft Store](https://www.microsoft.com/en-gb/store/p/wikivoyage-by-kiwix/9n5sb90q4jbj) or from [releases](https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.7-Wikivoyage), though the update of the Store's description of the app is still pending (still says 0.9.6 - this is normal, as the Store "front" is only updated once every 24 hours, whereas packages are updated as soon as they are certified).

**Comment by kelson42** [comment]
Good :) I have downloaded it and everything seems to work fine and last improvements are there :)

**Comment by Jaifroid** [comment]
Thanks for the report, @kelson42 . This is the same version as in the non-packaged (Kiwix JS) app, so no need now for you to test that app separately. The store update to plain Kiwix JS (to 0,9.7 beta) should be coming through later today.

**Comment by Jaifroid** [comment]
Early days, but here is some usage so far for Wikivoyage specifically. As this app is very much focused on English language and English-speaking travellers, I would expect Anglophone countries to predominate:
![image](https://user-images.githubusercontent.com/4304337/34818007-76c9254a-f6b1-11e7-8e1d-4db9d0e2e23d.png)

**Comment by Jaifroid** [comment]
I notice that German-language Wikivoyage ZIM (1GB) seems to be larger than English-language Wikivoyage (699Mb). This doesn't surprise me, as the Germans travel a lot, and German travel guides (book form) were always more detailed when I was a young traveller than English-language ones. May be a useful info point in terms of which languages to target.

**Comment by kelson42** [comment]
@Jaifroid I confirm that the Wikivoyage in German is the most active version of Wikivoyage.
