### ISSUE TITLE
Wikimed  custom app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#35]
I think it would be a good idea to publish a Wikimed Custom app because:
* Big Windows mobile audience in India
* Wikimed is our most successful custom app on Android
* The Wikivoyage custom app on Windows mobile has proven to work properly.

**Comment by Jaifroid** [comment]
Happy to do this next!

**Comment by kelson42** [comment]
@Jaifroid Nice Chrismas gift :) Thank you very much.
@Popolechien Could you pleaes advice us for the best ZIM file for it, branding, ...?

**Comment by Jaifroid** [comment]
@Popolechien @kelson42 I've reserved the name "WikiMed by Kiwix" (by analogy with "Wikivoyage by Kiwix") in the Microsoft Store. Let me know if you'd like me to reserve any other names.

Is the best ZIM file for the English-language version currently `wikipedia_en_medicine_novid_2017-12.zim`? There is another one, but it's much larger due to video content, I presume, which Kiwix JS can't yet display anyway. I'll keep an eye out for any January update, as it would be good to release with the very latest content.

**Comment by kelson42** [comment]
@Popolechien May you please help @Jaifroid here with both branding and content questions?

**Comment by Popolechien** [comment]
@Jaifroid I haven't looked but do we have an early idea of what type of device people are using most (mobile or desktop?). If mobile I would use http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nopic_nodet_2017-08.zim, which is significantly smaller and easier to download/store (the drawback being that it's from last August): you can also rename it Wikimed Mini in that case.
If desktop, then wikipedia_en_medicine_novid_2017-12.zim will do the trick. The zim file with videos is simply too big for most devices. Also re:branding "Wikimed" is enough as this particular brand is not Foundation owned. For logos, you can find them here: 
Wikimed Mini: https://commons.wikimedia.org/wiki/File:Wikimed_mini_EN.png
Wikimed: https://commons.wikimedia.org/wiki/File:MedLogoNoWiFiEn.png

@kelson42 it looks like the mini zim is the only one that wasn't updated in December when the others were. Any chance you could correct this in the next couple of weeks?

**Comment by Jaifroid** [comment]
Thanks for this helpful info @Popolechien . I can't seem to disambiguate the data (or not sure how) in the developer control panel regarding the different install devices, but I think it would make sense to have both a full WikiMed app and  WikiMed Mini, as you suggest. I have reserved both those names. I'll probably tackle the full version first, and do the Mini when there is an update to the ZIM.

**Comment by kelson42** [comment]
@Popolechien Fixed

**Comment by Jaifroid** [comment]
I have begun the process of customizing Kiwix JS Windows for a WikiMed release. Development is in https://github.com/kiwix/kiwix-js-windows/tree/Kiwix-JS-WikiMed-dev . It is mostly done except for icons and other visual assets.

**Comment by kelson42** [comment]
@Jaifroid Looks good to me.

**Comment by Popolechien** [comment]
Woah, you're going much further than the Wikimed project or any other app. Also, too many repeats (or too long a block of text) usually cause people to zone out.
I'd simplify to :

DISCLAIMER: The medical information in this app comes from Wikipedia.
<strong>Wikipedia does not give medical advice and Wikipedia is not a doctor.</strong> The information provided in this app is for the purposes of education and research. <em>This app must not be used as a substitute for professional medical advice.</em> 
                   
By using this app, you explicitly agree that you will not hold Kiwix, Wikipedia or anyone responsible for your use or misuse of the information provided to you.

(and then eventually a little "I agree" button)

**Comment by Jaifroid** [comment]
That's great @Popolechien -- I've not really done this kind of thing before, so going over the top is a sign of my caution! Your simplification is very helpful.

**Comment by Jaifroid** [comment]
As the WikiMed custom app is now in the Store, and I've opened a new issue to collect any feedback (#51), I think we can close this issue.

**Comment by kelson42** [comment]
@Jaifroid Thank you very much for all the good work on this. It is really great! We are a bit busy with a lot of administrative work around the project currently. Sorry for not being super reactive on that milestone. But @Popolechien and myself will start to advert it in the next days!
