### ISSUE TITLE
Geographical data for user sessions of the UWP app

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#372]
This may be of interest to @kelson42 and @Popolechien. Largest number of user sessions of the UWP (vanilla) app over the past year is in China (I guess that's just by dint of population size), followed by Israel (?!), Ethiopia, USA and Russia. Data are aggregate of the last 365 days, Feb 2022 to Feb 2023. NB, this is **only** the Microsoft Store app; I don't currently know how to get data for the Electron apps or the PWA.

![image](https://user-images.githubusercontent.com/4304337/219480973-cee92e8e-c22d-4c45-8a8a-3c6de85605cd.png)

**Comment by Jaifroid** [comment]
Looks like you can get the number of downloads of GitHub Releases, but not the geographical origin of those downloads. The data only go back to end of October 2022, i.e. less than 4 months, because I delete old releases quite regularly. Maybe I should keep them for a year?

![image](https://user-images.githubusercontent.com/4304337/219488721-a24507ba-0e4e-4949-9bd7-49a1669a0902.png)

**Comment by Popolechien** [comment]
@Jaifroid yes good idea. Do people get a notification when there is a new release?

**Comment by Jaifroid** [comment]
@Popolechien This depends on the app flavour:

* The UWP app is just updated by the Store (when the PC/tablet is online);
* The PWA updates itself when it is online, if one byte of the Service Worker has changed;
* The Electron and NWJS apps (optionally) either auto-update and notify the user to restart (.appimage and .exe), or else they display a banner in Configuration when there's a new version (.deb, .rpm, .zip) which gives the link to download the new package. The user can turn this functionality off for privacy reasons (e.g. don't want to be tracked, or it is dangerous to use the app from their location).

The fact that the apps do an update check (optionally) means it would be possible to track statistics in principle. For now, all we have is the number of package downloads from GitHub, and nothing from the PWA, because it runs in a ghcr.io container that is frequently rebuilt.

**Comment by Popolechien** [comment]
This is very useful, thank you.
