### ISSUE TITLE
Is electronuserland/builder still in use?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-js-windows#384]
Within https://github.com/kiwix/overview/issues/82, we looked at all repos for dependency on Docker Images that may migrate out of Docker Hub.

You reference `electronuserland/builder` in [Build-Electron.ps1](https://github.com/kiwix/kiwix-js-windows/blob/main/scripts/Build-Electron.ps1) but it's commented so it's unclear whether this is old code or an alternative.

[electronuserland](https://hub.docker.com/u/electronuserland/) is a *Community Organization* which means that next month it will not be allowed to push anymore (unless its status changes).
If you intend to rely on it in the future, you should find out their registry strategy and maybe update your image references.

https://github.com/kiwix/kiwix-js-windows/blob/c2ca4a952b5495ced47bd57b92aa07eedf6c6cd5/scripts/Build-Electron.ps1#L145-L173

**Comment by Jaifroid** [comment]
@rgaudin Thank you for opening this issue. I used to use Docker to build KJSW Linux apps on Windows. However this is no longer necessary or recommended, as a) it is much better for Windows users to build using Windows Subsystem for Linux, and b) Linux packages can be (and are) built on a real Linux runner on GitHub Actions, via npm install of electron-builder.

I'll remove or add a deprecation comment.
