### ISSUE TITLE
 docker-publish-action failing with "the server has asked for the client to provide credentials"

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#386]
While releasing a new version of KJSWL, the `docker-publish-action` is consistently failing at the "Restart the live webapp" stage. See https://github.com/kiwix/kiwix-js-windows/actions/runs/4693130079/jobs/8319703520 and https://github.com/kiwix/kiwix-js-windows/actions/runs/4693071572/jobs/8319604724. It has also failed a [third time](https://github.com/kiwix/kiwix-js-windows/actions/runs/4693633019/jobs/8320852735).

@rgaudin Have the credentials changed?

**Comment by rgaudin** [comment]
Right we issue credentials (certificate) for one year. Happy birthday! I'll generate a new one and update in github secrets

**Comment by rgaudin** [comment]
Fixed! See [this run](https://github.com/kiwix/kiwix-js-windows/actions/runs/4693633019).
We'll have the very same situation in a year. Not sure how we should address it. Ideas?

**Comment by rgaudin** [comment]
It's possible to create workflows attached to a cron and have them create tickets… See [this one](https://github.com/kiwix/k8s/blob/main/.github/workflows/weekly_routine.yaml) but an entry in your calendar is probably more appropriate

**Comment by Jaifroid** [comment]
Calendar entry added, but will look into auto ticket creation because it sounds cool... 😉
