### ISSUE TITLE
Windows app store icons are "ugly"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#42]
See the screenshot, it seems to have a (background) color problem (if you compare with the other/third app logo).
![firefox_screenshot_2018-01-11t16-12-10 122z](https://user-images.githubusercontent.com/1029718/34834618-c5b49a22-f6f2-11e7-9ccc-b236c6d699b7.png)

**Comment by Jaifroid** [comment]
OK I'll look into it. There are *so many* different sized assets required for the Store that it's hard to tell which ones precisely have ended up on that search page... That's the only page I've seen those versions of the icons on -- it seems to use a different version in multiple different places. It looks like a transparency issue.

**Comment by Jaifroid** [comment]
Success, I think I've determined which image needs to be provided in non-transparent form in order to prevent these ugly icons, and I implemented it with WikiMed 0.9.9. See screenshot.

![image](https://user-images.githubusercontent.com/4304337/36228404-08cb452e-11cc-11e8-91cd-7de284cca814.png)

**Comment by kelson42** [comment]
@Jaifroid cool :) Looks a lot better indeed. Could you fix Kiwix and Wikivoyage too?

**Comment by Jaifroid** [comment]
Will do with the next update(s).

**Comment by Jaifroid** [comment]
Nearly there. Just one more update to go. Wikivoyage icon will be done when the next Wikivoyage ZIM is released (if it is planned for early March -- if not, I'll release a code update).
![image](https://user-images.githubusercontent.com/4304337/36802880-0355f214-1cae-11e8-961f-09f34f4aca76.png)

**Comment by kelson42** [comment]
@Jaifroid Any chance to see Kiwix JS Windows 0.9.9.2 beta on the store soon?

**Comment by Jaifroid** [comment]
It's already in the store since Tuesday, @kelson42 .

But note there's a small regression #56, so if you were planning to do any testing, maybe you should wait till Monday or Tuesday, or else don't use the in-article word search feature as described in the issue.

**Comment by kelson42** [comment]
With the last update of Wikivoyage app for Windows mobile. This bug seems to have been completly fixed :)

**Comment by kelson42** [comment]
Hmm, seems to be still wrong here https://www.microsoft.com/en-us/search/result.aspx?q=kiwix

**Comment by Jaifroid** [comment]
Yes, I've been wondering if that search page will eventually update itself after the changes percolate through. If not, then I've done something wrong with the Wikivoyage one (I thought I'd done exactly the same). Will wait a couple of days more, as it **should** be fixed.

**Comment by Jaifroid** [comment]
OK, it looks like Microsoft's backend has now updated itself with the new image for Wikivoyage.

![image](https://user-images.githubusercontent.com/4304337/37455188-6e21cb7c-2834-11e8-936b-378a687fc1dd.png)

**Comment by kelson42** [comment]
Great, thank you @Jaifroid
