### ISSUE TITLE
Settings top bar button stays "clicked"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#44]
It is quite easy to get this buttong stuck as "clicked" status. This is for example easy to achieve by clicking on it during a page loading. I suspect here the whole handling of getting settings displayed and exiting is not so good. Exiting settings is done through a third party link, and I think we should at a least also work by clicking "out" the settings button.

**Comment by Jaifroid** [comment]
I think you're right -- the switching between the different menus isn't ideal. I can (and will) add some code to prevent the sticking here (some buttons such as the random button don't hide the settings page properly). But again a more generalized look at the menu switching should be undertaken in Kiwix JS. There is some discussion at https://github.com/kiwix/kiwix-js/issues/304.

**Comment by Jaifroid** [comment]
@kelson42 I've already implemented the "unsticking" part of this, but I haven't yet implemented a "clicking out" of the button to return you to the article you're reading. Not sure how intuitive that would be, but I agree it's a good idea to have it.

**Comment by Jaifroid** [comment]
This issue is now fixed in 0..9.9 beta in WikiMed and Kiwix JS. It has not yet been pushed to Wikivoyage. But I think the issue can be closed.

**Comment by kelson42** [comment]
@Jaifroid I confirm that this seems to work perfectly on my Lumia.
