### ISSUE TITLE
Provide a way for the device to read (out loud) the content of the article

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#45]
There is an API for this in UWP. I guess it's a bit esoteric, but could come into the category of assistive technology. I list it here in case anyone is particularly interested in such a feature.

**Comment by mossroy** [comment]
There is also a generic API that does it in recent browsers (but I did not test). See kiwix/kiwix-js#166

**Comment by Jaifroid** [comment]
Prototype code for reading aloud was added in https://github.com/kiwix/kiwix-js/pull/394 . Some issues need to be resolved (particularly accessing the language code) before it can be ported here.

**Comment by Jaifroid** [comment]
Closing this very old issue as it is better worked on upstream. It would be useful for accessibility, but I guess making the app [screen-reader accessible](https://github.com/kiwix/kiwix-js/issues/778) would be more important than having a custom reading feature.
