### ISSUE TITLE
WikiMed now in Microsoft Store

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#51]
After an initial alpha release for testing, I'm pleased to say that WikiMed Offline Medical Wikipedia is now available in the Microsoft Store:

GB Store: https://www.microsoft.com/en-gb/store/p/wikimed/9phjsnp1cz8j 

International link: https://www.microsoft.com/store/apps/9PHJSNP1CZ8J 

The changelog for this release is available here:
https://github.com/kiwix/kiwix-js-windows/blob/Kiwix-JS-WikiMed-dev/CHANGELOG.md

This release features much better handling of tabbed navigation, including the possibility of "unclicking" a tab to return to the currently loaded page (#44). There is also a fix for SVG extraction on devices with 1GB RAM (these would routinely crash, see #49). Packaged archive apps now hide the file selectors by default, and re-hide them on next launch if they are optionally unhidden (e.g. for downloading WikiMed in different languages). A quick, single-tap way to re-load the packaged archive is provided if a different archive has been loaded.

This issue is for any discussion or feedback about the release that doesn't merit a separate issue.

**Comment by Jaifroid** [comment]
It may be interesting to note that the Microsoft Store downloads a delta of the app when only small amounts of code have changed. This means that updates to the app code do not require a full download of the ZIM file. I specifically tested this by observing the behaviour between Store Release 0.9.8 (not publicised) and Store Release 0.9.9 (the current release). The store downloaded less than 10MB in order to update the full 1GB package.

However, I did experience the download of the delta getting "stuck" and signalling an error. Clicking on the refresh option fixed the error, but I had to do so about three times for the installation to complete successfully. I have observed this with other apps, so I think this is an issue with the delta system in the Store, and not and issue with this release.

Finally, although the package in the Store is now 0.9.9, the Store Listing still shows 0.9.8. Store listings are updated once per 24 hours, but packages update immediately.

**Comment by Popolechien** [comment]
Ok, I've posted the release on our Facebook and Twitter feeds.

**Comment by Jaifroid** [comment]
Thank you, @Popolechien !

**Comment by kelson42** [comment]
Made an announce on our mailin lists https://lists.wikimedia.org/pipermail/offline-l/2018-February/001446.html
