### ISSUE TITLE
Not enough padding on some pages

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#52]
A user on reddit has noted that the last few lines of the Ray Charles home page remain hidden under the UI. See screenshot.

![image](https://user-images.githubusercontent.com/4304337/36135093-b9d28b90-1080-11e8-9e9c-a6bdbb096fd6.png)

**Comment by kelson42** [comment]
One solution would be to have the bottom bar which disappear after a few seconds like on Android (dev version).

**Comment by mossroy** [comment]
That's true. And it probably happens on many other contents.
See discussion on kiwix/kiwix-js#337

**Comment by Jaifroid** [comment]
I think hiding the bottom bar (x seconds after scroll stop?) should be an option in the interface, like the current option for hiding the top bar (not currently controlled by scrolling). I've not been very happy with the code for hiding the top bar -- it's clunky and for some views (e.g. landscape on small-screen devices) bootstrap hides it anyway no matter what is selected in the interface. So this could be an opportunity for rethinking how that works and providing an option for the bottom bar.

But I don't think the only way the hidden content can be accessible is if the bar is hidden. It must be possible to access the content even if the user wants the bar on-screen at all times. So I think the only solution here is to add padding to the page. I actually [already do that](https://github.com/kiwix/kiwix-js-windows/blob/master/www/js/app.js#L1655), but this isn't a standard HTML page (it's an index produced programmatically) so the regex I use fails to match on this page. What happened here is that an earlier version of the regex did match this page, but it wasn't working on standard pages. So I changed the regex and failed to test it on Ray Charles's non-standard page.

**Comment by Jaifroid** [comment]
Issue fixed in repo. Will ship with 0.9.9.1.

![image](https://user-images.githubusercontent.com/4304337/36139523-b9711454-1095-11e8-99b1-261182ca17d4.png)

**Comment by Jaifroid** [comment]
Shipped with 0.9.9.2 beta.
