### ISSUE TITLE
Find a way to read indices for ZIM files

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#57]
Since UWP doesn't require picking a file to access it, it should be possible to read the index as a stream. Note that Stackexchange ZIMs in particular are fairly useless without a search mechanism other than title search. Finding things in Stackexchange is very hit-and-miss, unlike Wikipedia.

The best solution would be to port the zimlib tools with Emscripten. This should be done as part of https://github.com/kiwix/kiwix-js/issues/112 and https://github.com/kiwix/kiwix-js/issues/116.

Challenges, apart from the compilation and implementation are:

* Indices are not packaged along with the ZIM file, so it would be an extra download for Kiwix JS (Windows), but it could be included along with the ZIM for packaged ZIMs such as WikiMed and Wikivoyage;
* Indices are only provided inside a ZIP that contains the full split file, so there is no practical way of downloading just the Index at present;
* An alternative with past apps (x86) has been to allow the app to create an index. This is impractical on UWP, because the app may be tombstoned by the OS at any moment when it is not in the foreground. It is also impractical now with the size of many ZIMs.

**Comment by kelson42** [comment]
Best approach is probably to cross-compile the kiwix-lib to webasm.

**Comment by kelson42** [comment]
@Jaifroid See that a milestone 1.0 had already been set... but is that reasonable to want this feature in 1.0?

**Comment by Jaifroid** [comment]
@kelson42 I've changed it to Release 2.0. It's not reasonable, you're right. I've just modified the issues, to try to get the most important ones ready for a Release 1.0.

**Comment by kelson42** [comment]
Thinking twice about that ticket, I'm not sure sure it is still valid, because:
* That work has to be done on kiwix-js anyway (not on kiwix-js-windows), see the ticket given in description.
* We don't provide any more external indexes and we already partly don't support it anymore in other Kiwix versions
* We dont' provide any more ZIP files since 10 months

**Comment by Jaifroid** [comment]
OK, I'd already marked this as `upstream`. Will a different type of index be available in the future, if the current Xapian-based one is being deprecated? It's not so important for Wikipedia ZIMs, but Stackexchange ZIMs benefit hugely from having an index. Anyway, it's not particularly realistic at the moment for Kiwix-JS-Windows, and I could close this issue. If https://github.com/kiwix/kiwix-js/issues/116 is solved, could then re-open.

**Comment by kelson42** [comment]
@Jaifroid Xapian index is not going deprecated but now it is distributed within the ZIM file (not as external file/directory) for all our ZIM files.

**Comment by Jaifroid** [comment]
@kelson42 Is there a spec for the location and format of the word index inside the ZIM file, like the information given on https://wiki.openzim.org/wiki/ZIM_file_format for the different pointer lists?

**Comment by mossroy** [comment]
IMHO it's not worth spending time trying to read these indexes with a custom javascript implementation.
The first difficulty is that they are stored and read by xapian library, for which I do not know a pure javascript implementation.
Xapian could certainly be compiled with emscripten, but in this case it would be easier to compile the whole kiwix libraries, that encapsulate the low-level xapian : that's what kiwix/kiwix-js#116 tries to do

**Comment by kelson42** [comment]
Yes, like @mossroy says, there is almost no way to rebuild Xapian reader from scratch in JS. This would not be reasonable (too much work). Emscripten or similar is the way.

**Comment by Jaifroid** [comment]
It looks like someone has now done an Emscripten version of Xapian.

It's listed on the Emscripten GitHub at the very bottom of this page:

https://github.com/emscripten-core/emscripten/wiki/Porting-Examples-and-Demos

And it links to a Xapian PR from January:

https://github.com/xapian/xapian/pull/218

@mossroy Might it be worth experimenting with this?

**Comment by Jaifroid** [comment]
Additional info:
Compiled versions of Xapian are here (asm):
https://github.com/runbox/runbox7/blob/master/xapianasm.js 
and here (wasm):
https://github.com/runbox/runbox7/blob/master/xapianasm.wasm
And they are loaded from this TypeScript loader:
https://github.com/runbox/runbox7/blob/master/src/app/xapian/xapianwebloader.ts

Interesting (maybe!).

**Comment by kelson42** [comment]
@Jaifroid This is interesting because it means we should not have any problem to compile xapian with emscripten... but what should be compiled at the end is the libzim. Using xapian-js directly is probably not a good idea.

**Comment by Jaifroid** [comment]
I agree, much better to get libzim working. But maybe this could be an eventual fallback if the 2GB maximum read size of Emscripten WORKERFS cannot be overcome (see https://github.com/kiwix/kiwix-js/issues/116#issuecomment-304399154).

**Comment by Jaifroid** [comment]
I closed this and will re-open only if upstream attempts to compile libzim with Emscripten hit a significant roadblock.

**Comment by Jaifroid** [comment]
Just to add that there is now a JavaScript npm library for Xapian index reading (properly packaged version of the one referenced above). See https://www.npmjs.com/package/runbox7lib .
