### ISSUE TITLE
Some articles are blank in wikipedia_en_all_novid_2018-10.zim

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#68]
This is an issue with the encoding of `wikipedia_en_all_novid_2018-10.zim` as reported in https://github.com/openzim/mwoffliner/issues/462 . The specifics of the behaviour of Kiwix JS Windows with this ZIM are as reported by a user in the quote below. The user has subsequently downloaded `wikipedia_en_all_novid_2018-06.zim` and reports that the issue does not occur with the earlier ZIM. 

While the problem is with the ZIM, clearly Kiwix JS Windows should handle this situation in a more robust manner, since the same user reports that the pages load (with the same ZIM) on his iPhone. My guess here is that a regex or some other piece of code is causing an exception, which leads to an app crash. The crash is then handled by the global crash handling, resulting in a blank page. The crash probably occurs before the page is rendered (since rendering is delayed until stylesheets are loaded for performance reasons).

User report:

> Kiwix JS works perfectly well, on Wikipedia 'nopic', but just keeps falling over on the larger 'novid' file... it will load the file, random sometimes finds a page, sometimes not. The index seems OK - you can find the page desired, but then it just goes blank.
> 
> Anyway, that's how it is for me with the huge wikipedia_en_all_novid_2018-10.zim
> 
> I tried with the blue box show pictures on demand setting (brilliant idea) but the same - some pages do, and some don't.
> 
> And it's consistent, so must be something about the pages that won't load.
> 
> examples: 'Badger' loads fine, 'L'arlesiana' does not load.

**Comment by kelson42** [comment]
@Jaifroid Do we still have the bug with recent versions of the ZIM file? I mean withthe TOP selection for example?

**Comment by Jaifroid** [comment]
@kelson42 No, I haven't seen the bug. Well, the March full WikiMed English ZIM does have some images missing as I posted on mwoffliner, but it seems clear that's a problem with that ZIM, not with the reader. I can close this.
