### ISSUE TITLE
Zooming with touch causes a grey area to cover part of screen on PC

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#69]
This is a version of https://github.com/kiwix/kiwix-js/issues/163. A user has reported that zoom with touch on a touchscreen PC causes a grey area to appear that masks some of the article. I can reproduce the issue on a Surface Book (see screenshot below). This does not appear to occur on a Lumia 950XL. I think it will be necessary to fix https://github.com/kiwix/kiwix-js/issues/163 along with this, because zooming with touch is currently pretty useless due to the fact that the UI expands and disappears off-screen.

![image](https://user-images.githubusercontent.com/4304337/52161424-b8f0b280-26bc-11e9-831e-802f8a8fdc4f.png)

**Comment by Jaifroid** [comment]
In the meantime, the workaround for this issue is to zoom our or in with the provided "magnifying glass" icons, instead of with pinch / unpinch.

**Comment by Jaifroid** [comment]
It would be nice to eradicate this confusing zoom behaviour for Version 1.0, but it depends on the UWP framework (or, better, JavaScript) having a way to intercept the Zoom event and map it onto the zoom function the app supports. It might be better to work on this upstream, if such an event is defined.

**Comment by Jaifroid** [comment]
Solution to this is here https://github.com/kiwix/kiwix-js/issues/163#issuecomment-862988619.

**Comment by Jaifroid** [comment]
This is finally fixed...

**Comment by kelson42** [comment]
@Jaifroid small remark out of subject here but related to latest wikimed release you did a few hours ago. Unfortunately this very particular zim is broken, none of the homepage links work IMO. For the time being, you should try with June edition, I believe this version is Ok.

**Comment by Jaifroid** [comment]
@kelson42 Thanks for the warning! I'll investigate...

**Comment by Jaifroid** [comment]
OK, I hadn't noticed the issue because during the COVID-19 pandemic, I've been overriding the home page with a custom home page that includes a tailored collection of articles about the pandemic. I confirm that the links to the "Book" lists are not working, but due to the layout of the custom home page in the WikiMed UWP app, this would only be a very minor inconvenience for the user, as they are much more likely to click on one of the other exposed links (which do work)...

So unless you know of other crucial missing information, I think it's OK for me to keep this release (given the amount of time it takes to upload these large files....).

![image](https://user-images.githubusercontent.com/4304337/125204650-2df54880-e276-11eb-9642-25b66a9bc504.png)
