### ISSUE TITLE
Multiple Tabs?

### ISSUE THREAD

**Issue by ScyllaHide** [kiwix/kiwix-js-windows#70]
This is not an issue, but a feature request. I am using the maths zim file and it is necessary to really habe a few tabs open, when researching a mathematical definition, because maths is heavy cross-linked.

Right now there is only one Tab you can open.

**Comment by Jaifroid** [comment]
@ScyllaHide That's an interesting idea. What would be more useful, multiple windows or multiple tabs within the window? Rendering HTML to a hidden div and then showing it when the user clicks on a tab interface shouldn't be difficult -- the only difficulty is how best to represent the tab interface, since there is no native one for UWP apps. But there is a UWP API for multiple *windows* in an app.

I have to have a think about the best way of doing this, and if we use HTML/JavaScript to simulate a tab interface, whether it's best to develop it upstream in Kiwix JS.

**Comment by mossroy** [comment]
It could be an interesting enhancement, but I consider it as low priority for upstream kiwix-js.
Simulating tabs would not be that easy, as you'll have to deal with the multiple tabs in many use-cases, like back/forward buttons, choosing/changing the zim file, searching etc
There's also some work on the UI to make it easy to use in all form factors.
Using multiple windows might be easier to implement, but the user will have to select the ZIM file in each window.

It's a different context, but when kiwix-js is used as a browser extension, it is natively possible to open several browser tabs, with a different instance of kiwix-js inside each one. In this case, the browser tabs probably behave like your windows : the user has to select a ZIM file in each of them and they work independently.

**Comment by Jaifroid** [comment]
Thanks for pointing out those issues, @mossroy. @ScyllaHide, a basic tab interface may be possible for showing pages in the same ZIM, but as @mossroy says, there are questions surrounding how current UI elements would interact with it. A simpler possibility might be to allow a view-only window to be "broken out". This would be effectively spawning a new browser window (or maybe a new tab in some contexts) that would merely contain the HTML and embedded images, without any functionality (clicking on links would not navigate to them, for example). We could then have a breakout button/icon somewhere on the page. It might look a bit like this:

![image](https://user-images.githubusercontent.com/4304337/54979077-1b1db380-4f9a-11e9-9b24-9aee4a237098.png)

Would a view-only breakout window still be useful, @ScyllaHide?

**Comment by Jaifroid** [comment]
@ScyllaHide I have added a feature that extracts the html with embedded stylesheets and embedded images, and launches it in the browser (whichever browser is set to open html files). It enables side-by-side browsing of two pages as per screenshot below (left is a page showing in Kiwix JS Windows, right is a previously extracted page showing in Edge, but Firefox and Chromium also display the file identically). The main limitation is that the extracted page is entirely static. You cannot click on links to navigate to a new page: this can only be done in the Kiwix app. It is essentially a viewer only.

The code will be included in the next scheduled update.

![image](https://user-images.githubusercontent.com/4304337/55273380-613c8500-52c2-11e9-8ab6-3da7b685c138.png)

**Comment by ScyllaHide** [comment]
Sorry for not coming back.

Multiple tabs would be the best(like firefox has), but if this is to hard to achieve, then multiple windows would also work!

Thanks a lot!

**Comment by Jaifroid** [comment]
@ScyllaHide The breakout window is a bit of quick-fix, but it does the job. The only downside is that the resulting browser window can't currently be navigated (links won't take you anywhere) -- it's view only. But it works for research.

Tabs wouldn't allow side-by-side viewing -- only one tab could be open at a time in the app's interface, but it would make switching back-and-forth easy and quick.

**Comment by Jaifroid** [comment]
The break-out window option is in the main Kiwix JS Windows app in the Store (and has been for a few weeks). It will follow through to the WikiMed and Wikivoyage apps in due course.
