### ISSUE TITLE
Remove links to deprecated portable ZIP archives

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#76]
Portable archives with split ZIMs have been deprecated. We need to remove the code that offers the user to browse for the portable version of the ZIM they have discovered, since in nearly all cases there is no corresponding portable version any more.

**Comment by kelson42** [comment]
@Jaifroid Any chance to get this bug fixed soon? Portable ZIP files have been removed for a while now and this ticket seems easy to implement!

**Comment by Jaifroid** [comment]
@kelson42 I did this in https://github.com/kiwix/kiwix-js-windows/commit/eb5d2fc0189ec81dc90fabb1820f42555a68ad9d and it's in 0.9.9.97 Beta release, but for some reason this release is stuck in the Microsoft Store awaiting certification, and has been stuck there for more than a week... I think I need to cancel the certification and upload again. But I could close this anyway.

**Comment by Jaifroid** [comment]
@kelson42 A quick question on split ZIM files: is it now expected that the Reader will test the filesystem to see if it can store files greater than 4GB, and then chunk the downloads? I ask because I know even some brand new Android phones only support FAT32 filesystems on MicroSD cards, so there is still a need for splitting, unfortunately. Seems crazy in 2020...

**Comment by kelson42** [comment]
@Jaifroid Great. Thank you. For now, even the reader can not easily know where to split, but this will be the path hopefully to bring back the support of old and limited filesystems. This ticket is the most interesting on that topic: https://github.com/kiwix/kiwix-tools/issues/287. Good luck with the MS store,

**Comment by Jaifroid** [comment]
@kelson42 OK, thanks for the info!
