### ISSUE TITLE
Check support for Simplified Chinese

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#78]
I have had a (five-star) review from China asking for a Simplified Chinese version:

> Want to add Simplified Chinese, in addition Wiki Zim why not Simplified Chinese????

This issue is a note to check the situation with Chinese support in general and Simplified Chinese in particular.

**Comment by Popolechien** [comment]
@kelson42 I remember there was a ticket about converting from traditional to simplified chinese, but I can't find it. Any idea where that would be?

**Comment by kelson42** [comment]
@Popolechien I'm not sure to know in detail what you mean.

**Comment by Popolechien** [comment]
@kelson42 There are several versions of Chinese cohabiting on zh.wikipedia (mainland simplified, HongKong traditional, Macao traditional, Malaysian simplified, Singapore simplified, Taiwan traditional). The wiki switches easily from on to the other as only characters are impacted (not grammar).

I'm not entirely sure how this works on our end but from many reports I get (like the one above) we're not serving people with mainland traditional (大陆简体) content, which is both easier to use and has a lot more readers. It would be nice, therefore, to scrape it correctly. I also remember that this very issue was raised a while back, but I could not find it anywhere.
