### ISSUE TITLE
Make Kiwix JS Windows installable as a PWA

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#81]
By visiting https://kiwix.github.io/kiwix-js-windows/ in a Service-Worker capable browser, it is now possible to "install" Kiwix JS Windows as a Progressive Web App (PWA) for offline usage. Visiting this page installs a controller Service Worker that initially caches all the "shell" files of the app (e.g. `index.html`, `app.js`, `xzdec.js` etc.). If the user also enables "Service Worker mode" in Configuration, then the app will additionally cache the "expensive" assets for each ZIM (i.e. JavaScript and CSS), and these assets will be available across sessions, considerably speeding up reading of articles.

The PWA uses a "cache-first" strategy, only needing the server if it is missing one of its core files. On first launch all important shell files are pre-cached (although I am still missing a few to add to the list, e.g. KaTeX files), so theoretically it would only need one-time access to the server to undertake pre-caching. However, currently the app updates any file accessed from its cache by looking on the server to see if there is a newer copy (after having served the cached copy), but this behaviour is not necessary and is easy to eliminate once an update strategy has been devised. If the app is fully offline, it continues to function as normal.

Obviously the user still has to download a ZIM and pick it. And in a standard configuration, the user will still have to pick the ZIM on app load.

However, by installing the PWA inside a simple UWP shell, we get full access to Windows Runtime (WinRT) API, meaning that the user does not have to pick a ZIM, and we can include packaged ZIMs. Such an app would be installed from the Microsoft Store (or sideloaded), but would only work on Windows 10 machines. The main advantage of this approach over the current UWP app is that "Service Worker mode" is fully supported in this configuration, and so dynamic ZIM content can be accessed. The disadvantage is that some clients (Windows Mobile) do not have, and never will have, a Service-Worker enabled browser, and so are better off running the standard UWP app (otherwise the app will only run online for such users).

"Installation" of the app (not in a UWP shell) from Edge Chromium looks like below (after selecting the kebab menu top-right). A similar procedure is available from standard Chromium:

![image](https://user-images.githubusercontent.com/4304337/63530194-e472a780-c4fd-11e9-9ec8-e5ec12720832.png)

**Comment by Jaifroid** [comment]
Although not currently a target of this app, interestingly the PWA is installable on Android using either the standard Chrome browser or the Edge version for Android. However, the user is forced to select a ZIM on each startup of the app, and the engine does not seem optimized for Emscripten ASM, as it is much slower, even on a new device, than it is on Windows Mobile on a lower-powered, older device. It would be interesting to see if WASM runs faster in this context. In previous tests we found that there was no advantage in using WASM over ASM upstream, but maybe this needs to be revisited.

**Comment by fantasticfears** [comment]
BTW UAP with JavaScript support has been dropped from Visual Studio 2019. No new tools anymore.

**Comment by Jaifroid** [comment]
@fantasticfears Yes, VS2019 does not support UWP solutions of type `.jsproject`, and the recommended approach for the moment is either to use VS2017, which continues to support them and is still being bug-fixed, or to use VS Code and establish a toolchain for preparing the `.appxupload` for the Store and `.appxbundle` for sideloading. As you say, an alternative would be to run the entire JS code of this project inside a XAML webview. I haven't experimented with that. Are you able to share your approach for making this work?

**Comment by Jaifroid** [comment]
The other currently supported approach is to distribute the app as a PWA, which has access to the UWP WinRT runtime so long as it is packaged for the Store or for sideloading. MS provides [PWA Builder](https://www.pwabuilder.com/), which has a toolchain for packaging the app for the Store. I used this as a basis for adding PWA functionality to Kiwix JS Windows, which can now run as an offline-first PWA just by visiting its website. However, UWP APIs can only be accessed if the app is packaged as UWP, which again requires VS 2017 or a complex toolchain.

**Comment by fantasticfears** [comment]
Thanks for the information. I'm seeing a way to build Kiwix with UWP so I don't see how much I can help here. Giving some context, this is the first repo I checked. I have found that kiwix's core logic is almost packaged by C++. Using those existing c++ libs feels a more direct way to go. The major hassle is to compile their dependencies. Nevertheless, a WebView is still needed in the UWP app.
I don't have a concrete executable yet.

**Comment by Jaifroid** [comment]
Kiwix JS Windows is already a UWP in the Microsoft Store (and can be sideloaded - see Releases page). It is pretty performant on both Windows 10 PC and on Windows 10 Mobile. However, you're right that more could be achieved by compiling libzim C++ code for UWP with a XAML UI. You should perhaps look at the existing official Android app repo to see what's required at the compilation level. I'd be interested to hear of any progress!

**Comment by Jaifroid** [comment]
I've added a PWA "install experience". See screenshots. To test, visit https://kiwix.github.io/kiwix-js-windows/www/ in Edge Chromium or Chrome. Should also work in recent Firefox, but untested as yet.

![image](https://user-images.githubusercontent.com/4304337/72943580-50d42a00-3d6e-11ea-8ae1-8211b3c7827f.png)

![image](https://user-images.githubusercontent.com/4304337/72943794-dfe14200-3d6e-11ea-8cf6-18b09b68c6b8.png)

**Comment by Jaifroid** [comment]
I have also now released an experimental UWP version of this Progressive Web App. See https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.97-PWA. The advantage of packaging the PWA as a UWP is that it has access to the Windows RunTime (WinRT) and therefore can remember picked ZIM files between app loads, like the regular Store app. The advantage of the PWA over the regular Store app is that it has Service Worker support built-in (on modern platforms: SW support is not available, for example, on Windows 10 Mobile). This app will work on x86, x64 and ARM devices running Windows 10.

**Comment by Jaifroid** [comment]
The app runs well as a PWA, but still has some issues:

* After the app has installed itself, it reads its own files from the PWA Cache and  runs fully offline, but the offline-first strategy means that when an offline file is read, a fetch event is spawned to check the server for an updated copy (if internet connectivity is available). While this strategy keeps the app completely up-to-date, it's a bit paradoxical for an app intended to be used predominantly offline. It would be better, then, to check a single file only (`init.js`) and provide an update button when a new version is detected (or automatically update on next app launch);
* Asking the user to install while using the app, like in the screenshot above, is a bit annoying; the install button in Configuration is enough.

**Comment by Jaifroid** [comment]
I close this, and add separate out the remaining issues.
