### ISSUE TITLE
Create signed app packages for UWP apps

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#82]
Following on from #80, we can now create properly signed appxbundle packages for the three UWP apps: Kiwix JS, WikiMed and Wikivoyage. Kiwix JS release will be updated in the next few days. WikiMed and Wikivoyage will be updated when new ZIMs are available.

**Comment by Jaifroid** [comment]
When I create an app package for the Store, the version signed with the Kiwix certificate cannot be uploaded to the Store. I have to change the ownership an certificate back to the Store certificate, but then the package produced is untrusted for sideloading. Therefore, I will have to incorporate a separate signing stage for packages intended for sideloading.

**Comment by Jaifroid** [comment]
According to my tests, the package for the [latest release 0.9.9.96 beta](https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.96-beta) has been successfully signed and can be sideloaded by following the simplified instructions on the release page.

**Comment by kelson42** [comment]
> When I create an app package for the Store, the version signed with the Kiwix certificate cannot be uploaded to the Store. I have to change the ownership and certificate back to the Store certificate, but then the package produced is untrusted for sideloading. Therefore, I will have to incorporate a separate signing stage for packages intended for sideloading.

This is not really a surprise to me. App store use their own signature and trust chain. One of the reason is that this is cheaper (no use of external certification authority). An other is that they control the full chain from the distribution to the installation, so they can use a local trusted only certificate.

This is of course different if you don't use an app store.

You probably have to handle both cases separately. Have you been able to do so? With the CI?

**Comment by Jaifroid** [comment]
@kelson42 Thanks for the followup. I'm currently doing it manually as I'm the only developer for Kiwix JS Windows and the toolchain for packaging apps without Visual Studio doesn't look very well supported (there was a npm package, but people were complaining it had stopped working, and I can't find it now; there is also [makeappx tool](https://docs.microsoft.com/en-us/windows/msix/package/create-app-package-with-makeappx-tool)).

The test version of 0.9.9.96 wasn't a proper "Release" (via GitHub releases page), it was just a test compile. I released it at the end of December with some additional fixes, for all three apps, as shown on the GitHub page and in the Store.

Releases from the [GitHub Releases page](https://github.com/kiwix/kiwix-js-windows/releases) are signed with the Kiwix certificate (as of 0.9.9.96). Releases sent to the Store are signed with the Microsoft certificate. Therefore, to be sure of downloading a side-loadable release, please only get packages from the Releases page, not from AppPackages folder inside the Repo (which could be signed with the MS cert). Likewise, if you'd like to store backups of released packages elsewhere on Kiwix servers, please get them from the Releases page.

**Comment by kelson42** [comment]
@Jaifroid I have tested the "new" release and it works fine to me. I think we can consider this ticket as done. I have open a other one for the automation at #84.
