### ISSUE TITLE
Announcement: portable WikiMed EN version for Windows 7/8/10 (32bit-64bit)

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#85]
***EDIT: Look for updated packages in posts further down page.***

I have released a portable WikiMed (English) version (running on the included NWJS platform) for 32bit or 64bit editions of Windows 7/8/10:

* https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.97N-WikiMed

This includes the February 2020 `wikipedia_en_medicine_maxi_2020-02.zim`. The app is fully portable, and can be copied to and run from a thumb drive. The user does not need to pick the ZIM archive: it opens automatically when running the app.

Users running Windows 10 may prefer to use the Store app, which keeps itself up-to-date automatically: https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.97-WikiMed

Users who need a version for **Windows XP and Vista (32bit)** should use https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.97N and download their chosen ZIM archive from the app's Configuration page.

Features:

* Printing the article contents is supported (only tested on Windows 10)
* Download WikiMed archives in other languages from within the app
* Selected archive is remembered and automatically re-opened between sessions
* Last-visited page remembered between sessions (optional)
* In-page search / highlighting (search button/Ctrl-F/Alt-F)
* Optional dark theme for UI and content
* Equations typeset with KaTeX if original TeX string is available
* Transform layout between Wikipedia mobile or desktop styles
* Optionally disable images if PC/Tablet is slow
* Export page to view in browser (using optional breakout link)
* Service Worker mode is fully supported (only tested on Windows 10)

**Comment by Jaifroid** [comment]
This package has been updated with the latest WikiMed ZIM for March 2020. New package: https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.98N-WikiMed

**Comment by kelson42** [comment]
Sorry, I missed this annoucement. Great work!

**Comment by Jaifroid** [comment]
This package has been updated with the latest WikiMed ZIM for April 2020. New package:
https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.985N-WikiMed

**Comment by Jaifroid** [comment]
This portable package release has been updated with the latest WikiMed ZIM for 25 April 2020. New package: https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.99N-WikiMed
