### ISSUE TITLE
Wrong logo on https://kiwix.github.io/kiwix-js-windows/kiwix-js-uwp.html

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js-windows#95]
This page displays a deprecated logo. I did not even know that page existed and would not know where to update it.

Correct logo: https://commons.wikimedia.org/wiki/Category:Logos_of_Kiwix

**Comment by Jaifroid** [comment]
I can update that logo! Thanks for pointing it out.

**Comment by Jaifroid** [comment]
PS that page is just a redirection page to the latest release, but will update.

**Comment by Jaifroid** [comment]
Done.
