### ISSUE TITLE
Can not open some specific wikipedia pages, infinite loading

### ISSUE THREAD

**Issue by Parlin-Galanodel** [kiwix/kiwix-js-windows#96]
I can not open some pages via the kiwix-js reader on windows 10(2004) build 19041.450

The articles could not be loaded properly are Meson, Meson Physics.

**Comment by Jaifroid** [comment]
@Parlin-Galanodel The new release is now available from the Microsoft Store, and you can update to it from there. Please let me know if it resolves this issue for you once you've been able to test it.

**Comment by Parlin-Galanodel** [comment]
Thanks, man.  I just updated and tested it. Problem resolved!
