### ISSUE TITLE
New release: Kiwix JS Windows 0.9.9.992 beta

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#97]
A new release of Kiwix JS Windows UWP app is now available for sideloading from GitHub Releases, and is awaiting Certification in the Microsoft Store.

Signed GitHub package is available here:

https://github.com/kiwix/kiwix-js-windows/releases/tag/v0.9.9.992-beta

See the Changelog [here](https://github.com/kiwix/kiwix-js-windows/blob/master/CHANGELOG.md).

In particular, this release fixes #96.

**Comment by kelson42** [comment]
Done but I had to rename the release because it does not follow the Kiwix release naming scheme https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows_0.9.9.101.appxbundle

**Comment by Jaifroid** [comment]
Thank you @kelson42 ! Soon I will get on to a regular numbering scheme (major-minor), just as soon as I've achieved ZSTD decompression which is what I'll be working on now till end of August (fingers crossed).

**Comment by kelson42** [comment]
> Thank you @kelson42 ! Soon I will get on to a regular numbering scheme (major-minor), just as soon as I've achieved ZSTD decompression which is what I'll be working on now till end of August (fingers crossed).

@Jaifroid Great, waiting impatiently to move on with both of these points! Thx!

**Comment by Jaifroid** [comment]
> Done but I had to rename the release because it does not follow the Kiwix release naming scheme https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows_0.9.9.101.appxbundle

@Popolechien , @kelson42 has uploaded the new release to the Kiwix downloads server. Could you kindly update the link on https://www.kiwix.org/en/downloads/kiwix-reader/ ? The new file package link is: https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows_0.9.9.101.appxbundle . Many thanks!

**Comment by Jaifroid** [comment]
This now seems to be updated everywhere, so I'm closing this issue.

**Comment by kelson42** [comment]
@Popolechien You should not update the link here, please use the permalink https://download.kiwix.org/release/kiwix-js-windows/kiwix-js-windows.appxbundle

**Comment by Jaifroid** [comment]
@kelson42 I've just tested that permalink, and it downloads a package 0.9.9.990 which is two releases out of date.
How do we keep the permalink up to date?
